[workspace]
resolver = "2"
members = ["crates/*"]
default-members = ["crates/*"]


[workspace.package]
edition = "2024"

[workspace.dependencies]
ir-macros = { path = "crates/ir-macros" }
analyzer = { path = "crates/analyzer" }
graphmock = { path = "crates/graphmock" }
dot = { path = "crates/dot" }
cfg = { path = "crates/cfg" }
reader = { path = "crates/reader" }
ir = { path = "crates/ir" }
opt = { path = "crates/opt" }
entity-utils = { path = "crates/entity-utils" }
graphwalk = { path = "crates/graphwalk" }
strider-error = { path = "crates/strider-error" }
rsleigh = { path="../rsleigh" }

cranelift-bitset = "0.112.2"
cranelift-entity = "0.112.2"
smallvec = { version = "1.13.2", default-features = false, features = [
    "const_new",
] }
object = "0.38.1"

petgraph = "0.8.3"
thiserror = "2.0.18"
itertools = { version = "0.13.0", default-features = false }
expect-test = "1.5.0"

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic       = "deny"
unreachable = "deny"
todo        = "deny"

