[workspace]
resolver = "2"
members = ["crates/*"]
default-members = ["crates/*"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
strider-reader = { path = "crates/strider-reader" }
strider-target = { path = "crates/strider-target" }
dot = { path = "crates/dot" }
entity-utils = { path = "crates/entity-utils" }
graphwalk = { path = "crates/graphwalk" }
strider-ir = { path = "crates/strider-ir" }
strider-ir-test-utils = { path = "crates/strider-ir-test-utils" }
strider-lift = { path = "crates/strider-lift" }
strider-analyze = { path = "crates/strider-analyze" }
strider-pattern = { path = "crates/strider-pattern" }
rsleigh = { path = "../rsleigh" }

cranelift-bitset = "0.112.2"
cranelift-entity = "0.112.2"
smallvec = { version = "1.13.2", default-features = false, features = [
    "const_new",
] }
object = "0.38.1"

petgraph = "0.8.3"
thiserror = "2.0.18"
anyhow = "1.0"
itertools = { version = "0.13.0", default-features = false }
expect-test = "1.5.0"

[workspace.lints.clippy]
unwrap_used      = "deny"
expect_used      = "deny"
panic            = "deny"
unreachable      = "deny"
todo             = "deny"
redundant_closure = "warn"
map_unwrap_or    = "warn"
match_same_arms  = "warn"
must_use_candidate = "warn"
missing_errors_doc = "warn"

