//! `.pyi` generator for the macro-emitted reference pattern types.
//!
//! Run with:
//!
//! ```bash
//! cargo run -p strider-py --example stub_gen \
//!     --features stub_gen --no-default-features
//! ```
//!
//! The `--no-default-features` flag turns off pyo3's
//! `extension-module` feature so the resulting Rust binary actually
//! links libpython at load time.  `--features stub_gen` swaps in
//! `pyo3/auto-initialize` so `Python::with_gil(...)` works inside the
//! generator.
//!
//! Output goes to `crates/strider-py/strider/_generated/`, which is
//! gitignored.  The hand-written `strider/pattern.pyi` ships with the
//! wheel; the generated `.pyi` is the **test oracle** consumed by
//! `tests/python/test_reference_pyi.py` (mypy --strict).  A future
//! iteration will swap the hand-written stub for the generated one
//! once the macro covers every pattern type.
//!
//! ## Why an `[example]` and not a `[bin]`
//!
//! `examples/foo.rs` is built only on demand (`cargo run --example
//! foo`), so adding this target doesn't change the default
//! `cargo build` / `cargo test` flow the snapshot baselines depend on.
//! Adding a `[bin]` target would have unconditional implications
//! (manifest dependency reachability, dead-code lints, default
//! `cargo build --workspace` triggering binary linkage) we don't
//! want.

use std::fs;
use std::path::PathBuf;

use pyo3_stub_gen::Result;

/// Subdirectory under `python-source` that holds the generated stubs.
/// Kept separate from the hand-written `pattern.pyi` (which ships with
/// the wheel) so re-running `stub_gen` is a pure dev tool — no risk
/// of overwriting the shipped ABI surface.
const OUT_DIR: &str = "strider/_generated";

fn main() -> Result<()> {
    // `stub_info` is generated by `define_stub_info_gatherer!(stub_info)`
    // in `crates/strider-py/src/lib.rs`.  It reads pyproject.toml to
    // discover the `python-source` directory and emits one `.pyi`
    // per registered Python (sub-)module — but it writes directly to
    // `strider/*.pyi`, which would clobber the hand-written stubs.
    // We borrow `StubInfo`'s `modules` map and write to a sibling
    // directory ourselves.
    //
    // Lib name is `strider_py` (per Cargo.toml `[lib].name`) so the
    // rlib doesn't collide with the workspace `strider` orchestrator
    // crate.  The Python-side import name stays `strider` because
    // pyo3 + maturin rename the cdylib artefact at packaging time.
    let stub = strider_py::stub_info()?;

    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let out_root = manifest_dir.join(OUT_DIR);
    fs::create_dir_all(&out_root)?;

    for (mod_name, module) in &stub.modules {
        // `strider.pattern` -> `strider/pattern.pyi`, but rooted under
        // `OUT_DIR`.  We don't bother with submodule trees: every
        // module collected by pyo3-stub-gen is leaf-level.
        let rel = mod_name.replace('.', "/");
        let dest = out_root.join(format!("{rel}.pyi"));
        if let Some(parent) = dest.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&dest, format!("{module}"))?;
        println!("wrote {}", dest.display());
    }
    println!("Reference stubs generated under {}", out_root.display(),);
    Ok(())
}
