[package]
name = "ir"
version = "0.1.0"
edition.workspace = true

[dependencies]
rsleigh.workspace = true
cranelift-bitset.workspace = true
cranelift-entity.workspace = true
smallvec.workspace = true
graphwalk.workspace = true
entity-utils.workspace = true
itertools.workspace = true
dot.workspace = true
thiserror.workspace = true