[package]
name = "strider"
version = "0.1.0"
edition.workspace = true

[dependencies]
rsleigh.workspace = true
anyhow.workspace = true
target.workspace = true
ir.workspace = true
dot.workspace = true
cfg.workspace = true
opt.workspace = true
pcode-lift.workspace = true
pattern.workspace = true
reader.workspace = true
object.workspace = true

[lints]
workspace = true

[dev-dependencies]
expect-test.workspace = true
paste = "1"
ir = { workspace = true, features = ["test-utils"] }
criterion = { version = "0.7", features = ["html_reports"] }

[[bench]]
name = "scaling"
harness = false