[package]
name = "strider-lift"
version = "0.1.0"
edition.workspace = true

[dependencies]
strider-ir = { workspace = true }
dot.workspace = true
graphwalk.workspace = true
rsleigh.workspace = true
anyhow.workspace = true
strider-target.workspace = true
petgraph.workspace = true
rustc-hash = "2"

[dev-dependencies]
strider-ir-test-utils.workspace = true
strider-reader.workspace = true
object.workspace = true

[lints]
workspace = true
