[package]
name = "opt"
version = "0.1.0"
edition.workspace = true

[dependencies]
ir.workspace = true
pattern.workspace = true
reader.workspace = true
rsleigh.workspace = true
target.workspace = true
anyhow.workspace = true
ethnum.workspace = true
rustc-hash = { workspace = true }

[dev-dependencies]
criterion = { version = "0.7", features = ["html_reports"] }

[[bench]]
name = "constant_fold"
harness = false

[[bench]]
name = "known_bits"
harness = false

[[bench]]
name = "stack_store"
harness = false

[[bench]]
name = "default_pipeline"
harness = false

[lints]
workspace = true