[package]
name = "opt"
version = "0.1.0"
edition.workspace = true

[dependencies]
strider-analyze = { workspace = true }

[dev-dependencies]
criterion = { version = "0.7", features = ["html_reports"] }
strider-ir = { workspace = true, features = ["test-utils"] }
rsleigh = { workspace = true }
target = { workspace = true }
pattern = { workspace = true }
anyhow = { workspace = true }

[[bench]]
name = "constant_fold"
harness = false

[[bench]]
name = "known_bits"
harness = false

[[bench]]
name = "stack_store"
harness = false

[[bench]]
name = "default_pipeline"
harness = false

[lints]
workspace = true
