//! Shared error-wrapper machinery for strider crates.
//!
//! Every crate in the workspace that defines an error type wraps its
//! existing `thiserror` enum in a [`Error`-shaped wrapper] struct
//! generated by the [`define_error!`] macro. The wrapper carries:
//!
//! * a `Box<ErrorKind>` — the original enum, unchanged.
//! * an [`ErrorFields`] payload holding:
//!   * an [`std::backtrace::Backtrace`] captured at the point the error
//!     was first created (the "origin" of the error).
//!   * a [`LocationChain`] — a `Vec` of `&'static Location` values, one
//!     pushed at every `?` / `From::from` boundary the error crosses.
//!
//! The combination gives callers a Python-style traceback: a sequence of
//! `file:line:column` frames showing propagation, plus a stack backtrace
//! pointing at the origin. This is what the PyO3 layer (planned
//! `strider-py`) converts into a Python exception's `__traceback__`.

pub mod format;
#[macro_use]
mod wrapper;

pub use format::format_traceback;
pub use wrapper::{ErrorFields, LocationChain};
