//! Builder structs for [`crate::pat::Pat`].
//!
//! The three binary-op builders (`IntBinaryOpPat`, `BoolBinaryOpPat`,
//! `FloatBinaryOpPat`) and the four memory builders (`LoadPat`, `StorePat`,
//! `StackStorePat`, `StackStorePhiPat`) are hand-rolled so they can emit
//! trait-backed [`NodePat`]s directly.  The remaining builders for the
//! control family (Phi / Call / CallOther / Return / If / FunctionArg) are
//! still generated by the [`define_pat_builder!`] macro on the Legacy
//! `PatKind` dispatch path.

use std::sync::Arc;

use ir::node::NodeKind;
use ir::{BoolBinaryOp, FloatBinaryOp, IntBinaryOp};

use crate::matcher::commutativity::{
    is_commutative_bool_op, is_commutative_float_op, is_commutative_int_op,
};
use crate::pat::node_pat::{InputsSpec, NodePat};
use crate::pat::{Pat, int_const};
use crate::pat_macros::define_pat_builder;
use crate::var::{NodeVar, Var};

// ── Builder: IntBinaryOpPat ───────────────────────────────────────────────────

/// Builder for integer binary operation patterns.
///
/// Returned by [`crate::pat::int_binary`] and the shorthand constructors
/// ([`crate::pat::add`], [`crate::pat::sub`], [`crate::pat::mul`], …).  Call
/// `.into()` (or pass directly to any `impl Into<Pat>` parameter) to obtain a
/// [`Pat`].
pub struct IntBinaryOpPat {
    pub(super) op: IntBinaryOp,
    pub(super) lhs: Pat,
    pub(super) rhs: Pat,
    pub(super) ordered: bool,
}

impl IntBinaryOpPat {
    pub(crate) fn new(op: IntBinaryOp, lhs: Pat, rhs: Pat) -> Self {
        Self {
            op,
            lhs,
            rhs,
            ordered: false,
        }
    }

    /// Force the pattern to match operands in the stated order only.
    /// By default, commutative operators (`Add`, `Mul`, `And`, `Or`, `Xor`)
    /// will also try the reversed operand order.
    pub fn ordered(mut self) -> Self {
        self.ordered = true;
        self
    }
}

impl From<IntBinaryOpPat> for Pat {
    fn from(b: IntBinaryOpPat) -> Pat {
        let op = b.op;
        let commutative_at_construction = !b.ordered && is_commutative_int_op(op);
        let inputs = if commutative_at_construction {
            InputsSpec::fixed_commutative(b.lhs, b.rhs)
        } else {
            InputsSpec::fixed_ordered(vec![b.lhs, b.rhs])
        };
        Pat::from_dyn(Arc::new(NodePat {
            kind_match: Arc::new(move |ctx, node, _b| {
                matches!(ctx.graph.graph.node_kind(node), NodeKind::IntBinaryOp(x) if *x == op)
            }),
            inputs,
            post_match: None,
            output_var: None,
            node_var: None,
        }))
    }
}

// ── Builder: BoolBinaryOpPat ──────────────────────────────────────────────────

/// Builder for boolean binary operation patterns.
///
/// Returned by [`crate::pat::bool_binary`] and the shorthand constructors
/// ([`crate::pat::bool_and`], [`crate::pat::bool_or`],
/// [`crate::pat::bool_xor`]).  Call `.into()` or pass directly to any
/// `impl Into<Pat>` parameter.
pub struct BoolBinaryOpPat {
    pub(super) op: BoolBinaryOp,
    pub(super) lhs: Pat,
    pub(super) rhs: Pat,
    pub(super) ordered: bool,
}

impl BoolBinaryOpPat {
    pub(crate) fn new(op: BoolBinaryOp, lhs: Pat, rhs: Pat) -> Self {
        Self {
            op,
            lhs,
            rhs,
            ordered: false,
        }
    }

    /// Force the pattern to match operands in the stated order only.
    pub fn ordered(mut self) -> Self {
        self.ordered = true;
        self
    }
}

impl From<BoolBinaryOpPat> for Pat {
    fn from(b: BoolBinaryOpPat) -> Pat {
        let op = b.op;
        let commutative_at_construction = !b.ordered && is_commutative_bool_op(op);
        let inputs = if commutative_at_construction {
            InputsSpec::fixed_commutative(b.lhs, b.rhs)
        } else {
            InputsSpec::fixed_ordered(vec![b.lhs, b.rhs])
        };
        Pat::from_dyn(Arc::new(NodePat {
            kind_match: Arc::new(move |ctx, node, _b| {
                matches!(ctx.graph.graph.node_kind(node), NodeKind::BoolBinaryOp(x) if *x == op)
            }),
            inputs,
            post_match: None,
            output_var: None,
            node_var: None,
        }))
    }
}

// ── Builder: FloatBinaryOpPat ─────────────────────────────────────────────────

/// Builder for float binary operation patterns.
///
/// Returned by [`crate::pat::float_binary`] and the shorthand constructors
/// ([`crate::pat::float_add`], [`crate::pat::float_sub`],
/// [`crate::pat::float_mul`], [`crate::pat::float_div`]).  Call `.into()` or
/// pass directly to any `impl Into<Pat>` parameter to obtain a [`Pat`].
pub struct FloatBinaryOpPat {
    pub(super) op: FloatBinaryOp,
    pub(super) lhs: Pat,
    pub(super) rhs: Pat,
    pub(super) ordered: bool,
}

impl FloatBinaryOpPat {
    pub(crate) fn new(op: FloatBinaryOp, lhs: Pat, rhs: Pat) -> Self {
        Self {
            op,
            lhs,
            rhs,
            ordered: false,
        }
    }

    /// Force the pattern to match operands in the stated order only.
    /// By default, commutative operators (`Add`, `Mul`) will also try the
    /// reversed operand order.
    pub fn ordered(mut self) -> Self {
        self.ordered = true;
        self
    }
}

impl From<FloatBinaryOpPat> for Pat {
    fn from(b: FloatBinaryOpPat) -> Pat {
        let op = b.op;
        let commutative_at_construction = !b.ordered && is_commutative_float_op(op);
        let inputs = if commutative_at_construction {
            InputsSpec::fixed_commutative(b.lhs, b.rhs)
        } else {
            InputsSpec::fixed_ordered(vec![b.lhs, b.rhs])
        };
        Pat::from_dyn(Arc::new(NodePat {
            kind_match: Arc::new(move |ctx, node, _b| {
                matches!(ctx.graph.graph.node_kind(node), NodeKind::FloatBinaryOp(x) if *x == op)
            }),
            inputs,
            post_match: None,
            output_var: None,
            node_var: None,
        }))
    }
}

// ── Builder: LoadPat ──────────────────────────────────────────────────────────

/// Builder for `Load` node patterns.  Created by [`crate::pat::load`].
pub struct LoadPat {
    space: Option<rsleigh::VnSpace>,
    addr: Option<Pat>,
    output_var: Option<Var>,
    node_var: Option<NodeVar>,
}

impl LoadPat {
    pub(crate) fn new() -> Self {
        Self {
            space: None,
            addr: None,
            output_var: None,
            node_var: None,
        }
    }
    /// Restrict the match to loads in address space `s`.
    pub fn space(mut self, s: rsleigh::VnSpace) -> Self {
        self.space = Some(s);
        self
    }
    /// Constrain the load's address operand.
    pub fn addr(mut self, p: impl Into<Pat>) -> Self {
        self.addr = Some(p.into());
        self
    }
    /// Bind the load's value output (`NodeOutputId`) to `v`.
    pub fn capture_output(mut self, v: Var) -> Self {
        self.output_var = Some(v);
        self
    }
    /// Bind the load's node (`NodeId`) to `nv`.
    pub fn capture_node(mut self, nv: NodeVar) -> Self {
        self.node_var = Some(nv);
        self
    }
}

impl From<LoadPat> for Pat {
    fn from(b: LoadPat) -> Pat {
        let LoadPat {
            space,
            addr,
            output_var,
            node_var,
        } = b;
        // Load inputs = [mem(0), addr(1)].
        let mut indexed: Vec<(usize, Pat)> = Vec::new();
        if let Some(addr_pat) = addr {
            indexed.push((1, addr_pat));
        }
        Pat::from_dyn(Arc::new(NodePat {
            kind_match: Arc::new(move |ctx, node, _b| {
                matches!(
                    ctx.graph.graph.node_kind(node),
                    NodeKind::Load(actual) if space.is_none_or(|s| *actual == s)
                )
            }),
            inputs: InputsSpec::Indexed(indexed),
            post_match: None,
            output_var,
            node_var,
        }))
    }
}

// ── Builder: StorePat ─────────────────────────────────────────────────────────

/// Builder for `Store` node patterns.  Created by [`crate::pat::store`].
pub struct StorePat {
    space: Option<rsleigh::VnSpace>,
    addr: Option<Pat>,
    data: Option<Pat>,
    output_var: Option<Var>,
    node_var: Option<NodeVar>,
}

impl StorePat {
    pub(crate) fn new() -> Self {
        Self {
            space: None,
            addr: None,
            data: None,
            output_var: None,
            node_var: None,
        }
    }
    /// Restrict the match to stores in address space `s`.
    pub fn space(mut self, s: rsleigh::VnSpace) -> Self {
        self.space = Some(s);
        self
    }
    /// Constrain the store's address operand.
    pub fn addr(mut self, p: impl Into<Pat>) -> Self {
        self.addr = Some(p.into());
        self
    }
    /// Constrain the value being stored.
    pub fn data(mut self, p: impl Into<Pat>) -> Self {
        self.data = Some(p.into());
        self
    }
    /// Bind the store's memory output (`NodeOutputId`) to `v`.
    pub fn capture_output(mut self, v: Var) -> Self {
        self.output_var = Some(v);
        self
    }
    /// Bind the store's node (`NodeId`) to `nv`.
    pub fn capture_node(mut self, nv: NodeVar) -> Self {
        self.node_var = Some(nv);
        self
    }
}

impl From<StorePat> for Pat {
    fn from(b: StorePat) -> Pat {
        let StorePat {
            space,
            addr,
            data,
            output_var,
            node_var,
        } = b;
        // Store inputs = [mem(0), addr(1), data(2)].
        let mut indexed: Vec<(usize, Pat)> = Vec::new();
        if let Some(addr_pat) = addr {
            indexed.push((1, addr_pat));
        }
        if let Some(data_pat) = data {
            indexed.push((2, data_pat));
        }
        Pat::from_dyn(Arc::new(NodePat {
            kind_match: Arc::new(move |ctx, node, _b| {
                matches!(
                    ctx.graph.graph.node_kind(node),
                    NodeKind::Store(actual) if space.is_none_or(|s| *actual == s)
                )
            }),
            inputs: InputsSpec::Indexed(indexed),
            post_match: None,
            output_var,
            node_var,
        }))
    }
}

// ── Builder: StackStorePat ────────────────────────────────────────────────────

/// Builder for `StackStore` node patterns.  Created by [`crate::pat::stack_store`].
pub struct StackStorePat {
    space: Option<rsleigh::VnSpace>,
    offset: Option<i64>,
    data: Option<Pat>,
    output_var: Option<Var>,
    node_var: Option<NodeVar>,
}

impl StackStorePat {
    pub(crate) fn new() -> Self {
        Self {
            space: None,
            offset: None,
            data: None,
            output_var: None,
            node_var: None,
        }
    }
    /// Restrict the match to stack-stores in address space `s`.
    pub fn space(mut self, s: rsleigh::VnSpace) -> Self {
        self.space = Some(s);
        self
    }
    /// Match only the stack-store at the given SP-relative offset.
    pub fn offset(mut self, o: i64) -> Self {
        self.offset = Some(o);
        self
    }
    /// Constrain the stored value.
    pub fn data(mut self, p: impl Into<Pat>) -> Self {
        self.data = Some(p.into());
        self
    }
    /// Bind the stack-store's memory output (`NodeOutputId`) to `v`.
    pub fn capture_output(mut self, v: Var) -> Self {
        self.output_var = Some(v);
        self
    }
    /// Bind the stack-store's node (`NodeId`) to `nv`.
    pub fn capture_node(mut self, nv: NodeVar) -> Self {
        self.node_var = Some(nv);
        self
    }
}

impl From<StackStorePat> for Pat {
    fn from(b: StackStorePat) -> Pat {
        let StackStorePat {
            space,
            offset,
            data,
            output_var,
            node_var,
        } = b;
        // StackStore inputs = [memory(0), base(1), data(2)].
        let mut indexed: Vec<(usize, Pat)> = Vec::new();
        if let Some(data_pat) = data {
            indexed.push((2, data_pat));
        }
        Pat::from_dyn(Arc::new(NodePat {
            kind_match: Arc::new(move |ctx, node, _b| {
                matches!(
                    ctx.graph.graph.node_kind(node),
                    NodeKind::StackStore { space: actual_space, offset: actual_offset }
                        if space.is_none_or(|s| *actual_space == s)
                            && offset.is_none_or(|o| *actual_offset == o)
                )
            }),
            inputs: InputsSpec::Indexed(indexed),
            post_match: None,
            output_var,
            node_var,
        }))
    }
}

// ── Builder: StackStorePhiPat ─────────────────────────────────────────────────

/// Builder for `StackStorePhi` node patterns.  Created by [`crate::pat::stack_store_phi`].
pub struct StackStorePhiPat {
    space: Option<rsleigh::VnSpace>,
    offsets: Option<Vec<i64>>,
    data: Option<Pat>,
    output_var: Option<Var>,
    node_var: Option<NodeVar>,
}

impl StackStorePhiPat {
    pub(crate) fn new() -> Self {
        Self {
            space: None,
            offsets: None,
            data: None,
            output_var: None,
            node_var: None,
        }
    }
    pub fn space(mut self, s: rsleigh::VnSpace) -> Self {
        self.space = Some(s);
        self
    }
    pub fn data(mut self, p: impl Into<Pat>) -> Self {
        self.data = Some(p.into());
        self
    }
    pub fn capture_output(mut self, v: Var) -> Self {
        self.output_var = Some(v);
        self
    }
    pub fn capture_node(mut self, nv: NodeVar) -> Self {
        self.node_var = Some(nv);
        self
    }
    /// Match the per-branch offsets exactly.  The supplied list is sorted
    /// ascending before comparison, so caller order is irrelevant.
    pub fn offsets<I: IntoIterator<Item = i64>>(mut self, os: I) -> Self {
        let mut v: Vec<i64> = os.into_iter().collect();
        v.sort();
        self.offsets = Some(v);
        self
    }
}

impl From<StackStorePhiPat> for Pat {
    fn from(b: StackStorePhiPat) -> Pat {
        let StackStorePhiPat {
            space,
            offsets,
            data,
            output_var,
            node_var,
        } = b;
        // StackStorePhi inputs = [phi_token(0), memory(1), data(2)].
        let mut indexed: Vec<(usize, Pat)> = Vec::new();
        if let Some(data_pat) = data {
            indexed.push((2, data_pat));
        }
        Pat::from_dyn(Arc::new(NodePat {
            kind_match: Arc::new(move |ctx, node, _b| {
                let NodeKind::StackStorePhi {
                    space: actual_space,
                } = ctx.graph.graph.node_kind(node)
                else {
                    return false;
                };
                if let Some(expected_space) = space
                    && *actual_space != expected_space
                {
                    return false;
                }
                if let Some(expected_offsets) = &offsets {
                    let mut actual: Vec<i64> =
                        ctx.graph.graph.stack_phi_offsets(node).to_vec();
                    actual.sort();
                    if &actual != expected_offsets {
                        return false;
                    }
                }
                true
            }),
            inputs: InputsSpec::Indexed(indexed),
            post_match: None,
            output_var,
            node_var,
        }))
    }
}

// ── Builder: PhiPat ──────────────────────────────────────────────────────────

define_pat_builder! {
    /// Builder for `ControlPhi` node patterns.  Created by [`crate::pat::phi`] or [`crate::pat::phi_for`].
    pub struct PhiPat => PatKind::Phi {
        /// Restrict the match to phi nodes for varnode `vn`.
        opt vn: rsleigh::Vn as for_vn;
        /// Constrain the value arriving from predecessor slot `idx`.
        vec_pat inputs push input;
        /// Bind the phi's output (`NodeOutputId`) to `v`.
        opt output_var: Var as capture_output;
        /// Bind the phi's `NodeId` to `nv`.
        opt node_var: NodeVar as capture_node;
    }
}

// ── Builder: CallPat ──────────────────────────────────────────────────────────

define_pat_builder! {
    /// Builder for `Call` node patterns.  Created by [`crate::pat::call`].
    pub struct CallPat => PatKind::Call {
        /// Constrain the call target with an arbitrary pattern.
        pat target;
        /// Constrain argument at position `idx` (0-based, after ctrl and mem inputs).
        vec_pat args push arg;
        /// Capture or constrain the Call's return-value output at ABI position
        /// `idx` — e.g. `.ret_output(0, var(v))` binds `v` to the `NodeOutputId`
        /// of the calling convention's first return register (`rax` on x86_64,
        /// `x0` on AArch64).  The inner pattern should be `var(v)` or `any()`;
        /// richer patterns are matched against the value output but will
        /// typically fail because the Call itself produces the value.  If the
        /// ret reg at `idx` is callee-saved, it does not appear as a Call
        /// output and the match fails.
        vec_pat ret_outputs push ret_output;
        /// Bind the matched `Call` node to `nv`.
        opt node_var: NodeVar as capture;
    }
    extra {
        /// Constrain the call target to the literal address `addr`.
        pub fn at(self, addr: u64) -> Self {
            self.target(int_const(addr))
        }
    }
}

// ── Builder: CallOtherPat ─────────────────────────────────────────────────────

define_pat_builder! {
    /// Builder for `CallOther` node patterns.  Created by [`crate::pat::call_other`].
    pub struct CallOtherPat => PatKind::CallOther {
        /// Constrain the matched node to a specific user-op id.
        opt user_op_id: u64;
        /// Constrain argument at position `idx` (0-based, after ctrl and mem inputs).
        vec_pat args push arg;
        /// Bind the matched `CallOther` node to `nv`.
        opt node_var: NodeVar as capture;
    }
}

// ── Builder: RetPat ───────────────────────────────────────────────────────────

define_pat_builder! {
    /// Builder for `Return` node patterns.  Created by [`crate::pat::ret`].
    pub struct RetPat => PatKind::Return {
        /// Require that the return is preceded by a call matching `call` somewhere
        /// earlier on the same control path (backward walk).
        pat preceded_by;
        /// Constrain return value at position `idx` (0-based after the ctrl input).
        vec_pat ret_vals push ret_val;
        /// Bind the matched `Return` node to `nv`.
        opt node_var: NodeVar as capture;
    }
}

// ── Builder: FunctionArgPat ───────────────────────────────────────────────────

define_pat_builder! {
    /// Builder for `FunctionArg` node patterns.  Created by
    /// [`crate::pat::function_arg`], [`crate::pat::function_arg_any`],
    /// [`crate::pat::function_arg_reg`], [`crate::pat::function_arg_stack`].
    pub struct FunctionArgPat => PatKind::FunctionArg {
        /// Restrict the match to a specific ABI source (register or stack slot).
        opt source: ir::node::FunctionArgSource;
        /// Restrict the match to a specific argument index.
        opt index: u32;
        /// Bind the arg's value output (`NodeOutputId`) to `v`.
        opt output_var: Var as capture_output;
        /// Bind the arg's `NodeId` to `nv`.
        opt node_var: NodeVar as capture_node;
    }
}

// ── Builder: IfPat ────────────────────────────────────────────────────────────

define_pat_builder! {
    /// Builder for `If` node patterns.  Created by [`crate::pat::if_node`].
    pub struct IfPat => PatKind::If {
        /// Constrain the branch condition.
        pat cond;
        /// Require a node matching `p` to be reachable on the true branch (forward search).
        pat true_branch;
        /// Require a node matching `p` to be reachable on the false branch (forward search).
        pat false_branch;
        /// Bind the matched `If` node to `nv`.
        opt node_var: NodeVar as capture;
    }
}
