//! Builder structs for [`crate::pat::Pat`].
//!
//! The three hand-rolled binary-op builders (`IntBinaryOpPat`,
//! `BoolBinaryOpPat`, `FloatBinaryOpPat`) are structurally identical but kept
//! separate to preserve the distinct types exposed in the public API.  The
//! other eight builders are generated by the [`define_pat_builder!`] macro.

use std::sync::Arc;

use ir::node::NodeKind;
use ir::{BoolBinaryOp, FloatBinaryOp, IntBinaryOp};

use crate::matcher::commutativity::is_commutative_int_op;
use crate::pat::node_pat::{InputsSpec, NodePat};
use crate::pat::{Pat, PatKind, int_const};
use crate::pat_macros::define_pat_builder;
use crate::var::{NodeVar, Var};

// ── Builder: IntBinaryOpPat ───────────────────────────────────────────────────

/// Builder for integer binary operation patterns.
///
/// Returned by [`crate::pat::int_binary`] and the shorthand constructors
/// ([`crate::pat::add`], [`crate::pat::sub`], [`crate::pat::mul`], …).  Call
/// `.into()` (or pass directly to any `impl Into<Pat>` parameter) to obtain a
/// [`Pat`].
pub struct IntBinaryOpPat {
    pub(super) op: IntBinaryOp,
    pub(super) lhs: Pat,
    pub(super) rhs: Pat,
    pub(super) ordered: bool,
}

impl IntBinaryOpPat {
    pub(crate) fn new(op: IntBinaryOp, lhs: Pat, rhs: Pat) -> Self {
        Self {
            op,
            lhs,
            rhs,
            ordered: false,
        }
    }

    /// Force the pattern to match operands in the stated order only.
    /// By default, commutative operators (`Add`, `Mul`, `And`, `Or`, `Xor`)
    /// will also try the reversed operand order.
    pub fn ordered(mut self) -> Self {
        self.ordered = true;
        self
    }
}

impl From<IntBinaryOpPat> for Pat {
    fn from(b: IntBinaryOpPat) -> Pat {
        let op = b.op;
        let commutative_at_construction = !b.ordered && is_commutative_int_op(op);
        let inputs = if commutative_at_construction {
            InputsSpec::fixed_commutative(b.lhs, b.rhs)
        } else {
            InputsSpec::fixed_ordered(vec![b.lhs, b.rhs])
        };
        Pat::from_dyn(Arc::new(NodePat {
            kind_match: Arc::new(move |ctx, node, _b| {
                matches!(ctx.graph.graph.node_kind(node), NodeKind::IntBinaryOp(x) if *x == op)
            }),
            inputs,
            post_match: None,
            output_var: None,
            node_var: None,
        }))
    }
}

// ── Builder: BoolBinaryOpPat ──────────────────────────────────────────────────

/// Builder for boolean binary operation patterns.
///
/// Returned by [`crate::pat::bool_binary`] and the shorthand constructors
/// ([`crate::pat::bool_and`], [`crate::pat::bool_or`],
/// [`crate::pat::bool_xor`]).  Call `.into()` or pass directly to any
/// `impl Into<Pat>` parameter.
pub struct BoolBinaryOpPat {
    pub(super) op: BoolBinaryOp,
    pub(super) lhs: Pat,
    pub(super) rhs: Pat,
    pub(super) ordered: bool,
}

impl BoolBinaryOpPat {
    /// Force the pattern to match operands in the stated order only.
    pub fn ordered(mut self) -> Self {
        self.ordered = true;
        self
    }
}

impl From<BoolBinaryOpPat> for Pat {
    fn from(b: BoolBinaryOpPat) -> Pat {
        Pat::new(PatKind::BoolBinaryOp {
            op: b.op,
            lhs: b.lhs,
            rhs: b.rhs,
            ordered: b.ordered,
        })
    }
}

// ── Builder: FloatBinaryOpPat ─────────────────────────────────────────────────

/// Builder for float binary operation patterns.
///
/// Returned by [`crate::pat::float_binary`] and the shorthand constructors
/// ([`crate::pat::float_add`], [`crate::pat::float_sub`],
/// [`crate::pat::float_mul`], [`crate::pat::float_div`]).  Call `.into()` or
/// pass directly to any `impl Into<Pat>` parameter to obtain a [`Pat`].
pub struct FloatBinaryOpPat {
    pub(super) op: FloatBinaryOp,
    pub(super) lhs: Pat,
    pub(super) rhs: Pat,
    pub(super) ordered: bool,
}

impl FloatBinaryOpPat {
    /// Force the pattern to match operands in the stated order only.
    /// By default, commutative operators (`Add`, `Mul`) will also try the
    /// reversed operand order.
    pub fn ordered(mut self) -> Self {
        self.ordered = true;
        self
    }
}

impl From<FloatBinaryOpPat> for Pat {
    fn from(b: FloatBinaryOpPat) -> Pat {
        Pat::new(PatKind::FloatBinaryOp {
            op: b.op,
            lhs: b.lhs,
            rhs: b.rhs,
            ordered: b.ordered,
        })
    }
}

// ── Builder: LoadPat ──────────────────────────────────────────────────────────

define_pat_builder! {
    /// Builder for `Load` node patterns.  Created by [`crate::pat::load`].
    pub struct LoadPat => PatKind::Load {
        /// Restrict the match to loads in address space `s`.
        opt space: rsleigh::VnSpace;
        /// Constrain the load's address operand.
        pat addr;
        /// Bind the load's value output (`NodeOutputId`) to `v`.
        opt output_var: Var as capture_output;
        /// Bind the load's node (`NodeId`) to `nv`.
        opt node_var: NodeVar as capture_node;
    }
}

// ── Builder: StorePat ─────────────────────────────────────────────────────────

define_pat_builder! {
    /// Builder for `Store` node patterns.  Created by [`crate::pat::store`].
    pub struct StorePat => PatKind::Store {
        /// Restrict the match to stores in address space `s`.
        opt space: rsleigh::VnSpace;
        /// Constrain the store's address operand.
        pat addr;
        /// Constrain the value being stored.
        pat data;
        /// Bind the store's memory output (`NodeOutputId`) to `v`.
        opt output_var: Var as capture_output;
        /// Bind the store's node (`NodeId`) to `nv`.
        opt node_var: NodeVar as capture_node;
    }
}

// ── Builder: StackStorePat ────────────────────────────────────────────────────

define_pat_builder! {
    /// Builder for `StackStore` node patterns.  Created by [`crate::pat::stack_store`].
    pub struct StackStorePat => PatKind::StackStore {
        /// Restrict the match to stack-stores in address space `s`.
        opt space: rsleigh::VnSpace;
        /// Match only the stack-store at the given SP-relative offset.
        opt offset: i64;
        /// Constrain the stored value.
        pat data;
        /// Bind the stack-store's memory output (`NodeOutputId`) to `v`.
        opt output_var: Var as capture_output;
        /// Bind the stack-store's node (`NodeId`) to `nv`.
        opt node_var: NodeVar as capture_node;
    }
}

// ── Builder: StackStorePhiPat ─────────────────────────────────────────────────

define_pat_builder! {
    /// Builder for `StackStorePhi` node patterns.  Created by [`crate::pat::stack_store_phi`].
    pub struct StackStorePhiPat => PatKind::StackStorePhi {
        opt space: rsleigh::VnSpace;
        opt_field offsets: Vec<i64>;
        pat data;
        opt output_var: Var as capture_output;
        opt node_var: NodeVar as capture_node;
    }
    extra {
        /// Match the per-branch offsets exactly.  The supplied list is sorted
        /// ascending before comparison, so caller order is irrelevant.
        pub fn offsets<I: IntoIterator<Item = i64>>(mut self, os: I) -> Self {
            let mut v: Vec<i64> = os.into_iter().collect();
            v.sort();
            self.offsets = Some(v);
            self
        }
    }
}

// ── Builder: PhiPat ──────────────────────────────────────────────────────────

define_pat_builder! {
    /// Builder for `ControlPhi` node patterns.  Created by [`crate::pat::phi`] or [`crate::pat::phi_for`].
    pub struct PhiPat => PatKind::Phi {
        /// Restrict the match to phi nodes for varnode `vn`.
        opt vn: rsleigh::Vn as for_vn;
        /// Constrain the value arriving from predecessor slot `idx`.
        vec_pat inputs push input;
        /// Bind the phi's output (`NodeOutputId`) to `v`.
        opt output_var: Var as capture_output;
        /// Bind the phi's `NodeId` to `nv`.
        opt node_var: NodeVar as capture_node;
    }
}

// ── Builder: CallPat ──────────────────────────────────────────────────────────

define_pat_builder! {
    /// Builder for `Call` node patterns.  Created by [`crate::pat::call`].
    pub struct CallPat => PatKind::Call {
        /// Constrain the call target with an arbitrary pattern.
        pat target;
        /// Constrain argument at position `idx` (0-based, after ctrl and mem inputs).
        vec_pat args push arg;
        /// Capture or constrain the Call's return-value output at ABI position
        /// `idx` — e.g. `.ret_output(0, var(v))` binds `v` to the `NodeOutputId`
        /// of the calling convention's first return register (`rax` on x86_64,
        /// `x0` on AArch64).  The inner pattern should be `var(v)` or `any()`;
        /// richer patterns are matched against the value output but will
        /// typically fail because the Call itself produces the value.  If the
        /// ret reg at `idx` is callee-saved, it does not appear as a Call
        /// output and the match fails.
        vec_pat ret_outputs push ret_output;
        /// Bind the matched `Call` node to `nv`.
        opt node_var: NodeVar as capture;
    }
    extra {
        /// Constrain the call target to the literal address `addr`.
        pub fn at(self, addr: u64) -> Self {
            self.target(int_const(addr))
        }
    }
}

// ── Builder: CallOtherPat ─────────────────────────────────────────────────────

define_pat_builder! {
    /// Builder for `CallOther` node patterns.  Created by [`crate::pat::call_other`].
    pub struct CallOtherPat => PatKind::CallOther {
        /// Constrain the matched node to a specific user-op id.
        opt user_op_id: u64;
        /// Constrain argument at position `idx` (0-based, after ctrl and mem inputs).
        vec_pat args push arg;
        /// Bind the matched `CallOther` node to `nv`.
        opt node_var: NodeVar as capture;
    }
}

// ── Builder: RetPat ───────────────────────────────────────────────────────────

define_pat_builder! {
    /// Builder for `Return` node patterns.  Created by [`crate::pat::ret`].
    pub struct RetPat => PatKind::Return {
        /// Require that the return is preceded by a call matching `call` somewhere
        /// earlier on the same control path (backward walk).
        pat preceded_by;
        /// Constrain return value at position `idx` (0-based after the ctrl input).
        vec_pat ret_vals push ret_val;
        /// Bind the matched `Return` node to `nv`.
        opt node_var: NodeVar as capture;
    }
}

// ── Builder: FunctionArgPat ───────────────────────────────────────────────────

define_pat_builder! {
    /// Builder for `FunctionArg` node patterns.  Created by
    /// [`crate::pat::function_arg`], [`crate::pat::function_arg_any`],
    /// [`crate::pat::function_arg_reg`], [`crate::pat::function_arg_stack`].
    pub struct FunctionArgPat => PatKind::FunctionArg {
        /// Restrict the match to a specific ABI source (register or stack slot).
        opt source: ir::node::FunctionArgSource;
        /// Restrict the match to a specific argument index.
        opt index: u32;
        /// Bind the arg's value output (`NodeOutputId`) to `v`.
        opt output_var: Var as capture_output;
        /// Bind the arg's `NodeId` to `nv`.
        opt node_var: NodeVar as capture_node;
    }
}

// ── Builder: IfPat ────────────────────────────────────────────────────────────

define_pat_builder! {
    /// Builder for `If` node patterns.  Created by [`crate::pat::if_node`].
    pub struct IfPat => PatKind::If {
        /// Constrain the branch condition.
        pat cond;
        /// Require a node matching `p` to be reachable on the true branch (forward search).
        pat true_branch;
        /// Require a node matching `p` to be reachable on the false branch (forward search).
        pat false_branch;
        /// Bind the matched `If` node to `nv`.
        opt node_var: NodeVar as capture;
    }
}
