[package]
name = "entity-utils"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "cranelift-entity helpers: dense entity sets, worklists and interners."
repository.workspace = true
rust-version.workspace = true

[dependencies]
cranelift-bitset.workspace = true
cranelift-entity.workspace = true
rustc-hash.workspace = true

[lints]
workspace = true
