"""Type stubs for strider.pattern — the match-side pattern DSL.

`Pat` is the LHS of a `find` / `rewrite` query (match-only affordances:
`.when()`, commutativity, `.of_width()`, `.value_ty()`, wildcards). For a
rewrite RHS (`replace=`), use the build-side `strider.template` module and
its `Template` type instead — `Function.rewrite`/`rewrite_all` type
`replace` as `Template`. A bare `Pat` is still accepted there for
back-compat (only its build-valid subset compiles: no `.when`, no
wildcard, no commutativity), but `strider.template` is the documented
path.
"""

from __future__ import annotations

from typing import Any, Callable, List, Literal, Optional, Union

from ..ir import Node
from ..sleigh import Vn

#: Value-type names accepted by `Pat.value_ty` and returned by
#: `Node.value_type` / `Match.value_type`. Matched case-insensitively at
#: runtime; these are the canonical spellings.
ValueTy = Literal[
    "i1", "i8", "i16", "i32", "i48", "i64", "i80", "i128", "i256", "i512",
    "f32", "f64", "f80",
]

#: `IntCmpOp` variant names accepted by `int_cmp`. The short aliases
#: `"eq"` / `"lt"` / `"slt"` are equivalent to `"Equal"` / `"Less"` /
#: `"Sless"`. Matched case-insensitively at runtime.
IntCmpOpName = Literal[
    "Equal", "Less", "Sless", "Carry", "Scarry", "Sborrow", "eq", "lt", "slt",
]

#: Extend-op names accepted by `extend`.
ExtendOpName = Literal[
    "zero", "zero_extend", "ZeroExtend", "sign", "sign_extend", "SignExtend",
]

class Match:
    """`Node` is the single source of truth for per-node reads; every
    value/op reader below is a thin forwarder to `self.node(key).<reader>()`
    (returning `None` when `key` is unbound)."""

    @property
    def root(self) -> int:
        """The root node where the top-level pattern matched, as a `u32`
        node id.  Convenience for the single-pattern case — see `roots` for a
        joined (list) query."""
        ...
    @property
    def roots(self) -> List[int]:
        """The per-input-pattern root node ids — one entry per pattern passed
        to the query (`[root]` for a single-pattern query)."""
        ...
    def const_uint(self, key: Any) -> Optional[int]:
        """Thin forwarder to `Node.const_uint()`."""
        ...
    def const_int(self, key: Any) -> Optional[int]:
        """Thin forwarder to `Node.const_int()`."""
        ...
    def const_bool(self, key: Any) -> Optional[bool]:
        """Thin forwarder to `Node.const_bool()`."""
        ...
    def float_bits(self, key: Any) -> Optional[int]:
        """Thin forwarder to `Node.float_bits()`."""
        ...
    def has(self, key: Any) -> bool: ...
    def op(self, key: Any) -> Optional[str]:
        """The operation variant of the node bound to `key` — `"Add"`,
        `"Less"`, `"Neg"` — or `None` when `key` is unbound or names a node
        that carries no operation. Thin forwarder to `Node.op()`.

        One accessor covers every op family (integer / float, binary /
        unary / compare); pair it with `value_type` to tell a boolean op
        (`Xor` at `I1`) from a wide bitwise one."""
        ...
    def value_type(self, key: Any) -> Optional[str]:
        """The value-output type of the node bound to `key` — `"I1"`,
        `"I64"`, `"F64"` — or `None` when `key` is unbound or names a node
        with no value output. Thin forwarder to `Node.value_type()`."""
        ...
    def vn(self, key: Any) -> Optional[Vn]:
        """Recover the varnode bound by `key` (InitialVar / `Call` /
        `CallOther` clobber output), else `None`.  Thin forwarder to
        `Node.vn()`."""
        ...
    def asm_fingerprint(self, key: Any) -> List[int]:
        """Thin forwarder to `Node.asm_fingerprint()`; `[]` when `key` is unbound."""
        ...
    def node(self, key: Any) -> Optional[Node]:
        """A `Node` handle on the node bound to `key` (a `Capture` or
        string capture-name), or `None` when `key` is unbound.  Every
        other reader on `Match` is built on top of this resolution."""
        ...
    def __getitem__(self, key: Any) -> Any: ...
    def __contains__(self, key: Any) -> bool: ...

class Capture:
    """Opaque capture variable; bind a matched node and read it back
    from the `Match`."""
    def __init__(self) -> None: ...

class CastMask:
    """Bitset selecting which value-passthrough cast `NodeKind`s the
    matcher walks through transparently.  Compose with `|`; pass to
    `Function.find_all(pat, ignore_casts_mask=...)`."""
    @classmethod
    def zero_extend(cls) -> CastMask: ...
    @classmethod
    def sign_extend(cls) -> CastMask: ...
    @classmethod
    def extend(cls) -> CastMask: ...
    @classmethod
    def truncate(cls) -> CastMask: ...
    @classmethod
    def int_bits_to_float(cls) -> CastMask: ...
    @classmethod
    def float_bits_to_int(cls) -> CastMask: ...
    @classmethod
    def all(cls) -> CastMask: ...
    @classmethod
    def none(cls) -> CastMask: ...
    def bits(self) -> int: ...
    def __or__(self, other: CastMask) -> CastMask: ...
    def __and__(self, other: CastMask) -> CastMask: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Pat:
    """Opaque finalised match pattern — the LHS of a `find` / `rewrite`
    query.  Built by the free constructors and chained via `.capture` /
    `.cap` / `.when` / `.ordered` / `.of_width` / `.value_ty` /
    `.bool_valued`.  For the rewrite RHS, build a `strider.template.Template`
    instead (see that module)."""
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def ordered(self) -> Pat: ...
    def of_width(self, n: int) -> Pat:
        """OUTPUT-side: constrain this value's own output to `n` bits. The
        free-function form is `value_of_width(n)`. For the INPUT side, see
        `inputs_of_width(n, inner)`."""
        ...
    def value_ty(self, ty: ValueTy) -> Pat:
        """OUTPUT-side: constrain this value's own output type by name."""
        ...
    def bool_valued(self) -> Pat:
        """OUTPUT-side: constrain this value's output to a boolean (1-bit
        `I1`). Exactly `of_width(1)`, named for intent. INCLUDES
        comparisons; for "operates on bools", see `bool_inputs(inner)`."""
        ...

# All builders accept str | Capture | Pat (or one of the typed builders
# below) for sub-patterns.  The typed-builder variants are auto-finalised
# at field-setter call sites — see `CallPat.into_pat()` for the explicit
# form.  This union mirrors the Rust `PatLike` `FromPyObject` enum.
PatLike = Union[
    str,
    Capture,
    Pat,
    "CallPat",
    "CallOtherPat",
    "RetPat",
    "IfPat",
    "LoadPat",
    "StorePat",
    "PhiPat",
    "MemPhiPat",
    "EntryPat",
    "RegionPat",
    "IndirectBranchPat",
    "UnreachablePat",
    "SwitchPat",
    "FunctionArgPat",
    "IntBinaryPat",
    "FloatBinaryPat",
    "BoolBinaryPat",
]

# ── Typed family-dispatcher builder types ──────────────────────────────

class IntBinaryPat:
    """Builder for an integer binary-op pattern (returned by
    `int_binary`).  `.capture` / `.cap` / `.when` / `.ordered` are
    chainable (they return the builder, which nests directly as a value
    operand); `.into_pat()` finalises to a `Pat`."""
    def ordered(self) -> IntBinaryPat: ...
    def capture(self, c: Capture) -> IntBinaryPat: ...
    def cap(self, name: str) -> IntBinaryPat: ...
    def when(self, f: Callable[[Match], bool]) -> IntBinaryPat: ...
    def into_pat(self) -> Pat: ...

class FloatBinaryPat:
    """Builder for a float binary-op pattern (returned by
    `float_binary`).  `.capture` / `.cap` / `.when` / `.ordered` are
    chainable (they return the builder, which nests directly as a value
    operand); `.into_pat()` finalises to a `Pat`."""
    def ordered(self) -> FloatBinaryPat: ...
    def capture(self, c: Capture) -> FloatBinaryPat: ...
    def cap(self, name: str) -> FloatBinaryPat: ...
    def when(self, f: Callable[[Match], bool]) -> FloatBinaryPat: ...
    def into_pat(self) -> Pat: ...

class BoolBinaryPat:
    """Builder for a boolean binary-op pattern (returned by
    `bool_binary`).  Booleans are the 1-bit integer `I1`, so this builds
    an `IntBinaryOp` (`And` / `Or` / `Xor`) at `I1` with an `I1`-output
    guard (it never matches a same-shaped wide integer op).  `.capture` /
    `.cap` / `.when` / `.ordered` are chainable (they return the builder,
    which nests directly as a value operand); `.into_pat()` finalises to a
    `Pat`."""
    def ordered(self) -> BoolBinaryPat: ...
    def capture(self, c: Capture) -> BoolBinaryPat: ...
    def cap(self, name: str) -> BoolBinaryPat: ...
    def when(self, f: Callable[[Match], bool]) -> BoolBinaryPat: ...
    def into_pat(self) -> Pat: ...

class CallPat:
    """Builder for `Call` node patterns.  Returned by `call()`.

    Field-setter methods (`at`, `at_any`, `target`, `arg`) return the same
    builder for chaining; finaliser methods (`capture`, `cap`, `when`,
    `into_pat`) return a `Pat`.

    `Function.find_all` / `Function.rewrite` accept un-finalised builders
    via `PatLike`, so `g.find_all(call().arg(0, int_const(8)))` works
    without an explicit `.into_pat()`.
    """
    def at(self, addr: int) -> "CallPat": ...
    def at_any(self, addrs: List[int]) -> "CallPat": ...
    def target(self, p: PatLike) -> "CallPat": ...
    def arg(self, idx: int, p: PatLike) -> "CallPat": ...
    def any_input(self, p: PatLike) -> "CallPat": ...
    def mem(self, p: PatLike) -> "CallPat": ...
    def res(self) -> "CallPat": ...
    def output(self, slot: int) -> "CallOutputPat": ...
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def into_pat(self) -> Pat: ...

class CallOtherPat:
    """Builder for `CallOther` node patterns.  Returned by `call_other()`.

    Chain `.user_op_id(v)` to constrain the user-op id, `.name(s)` to
    constrain the user-op name (read from the side table), and
    `.arg(idx, p)` for individual arguments.
    """
    def user_op_id(self, v: int) -> "CallOtherPat": ...
    def name(self, n: str) -> "CallOtherPat": ...
    def arg(self, idx: int, p: PatLike) -> "CallOtherPat": ...
    def ctrl(self, p: PatLike) -> "CallOtherPat": ...
    def mem(self, p: PatLike) -> "CallOtherPat": ...
    def any_input(self, p: PatLike) -> "CallOtherPat": ...
    def res(self) -> "CallOtherPat": ...
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def into_pat(self) -> Pat: ...

class RetPat:
    """Builder for `Return` node patterns.  Returned by `ret()`.

    Chain `.preceded_by(p)` to match Returns whose direct ctrl
    predecessor is `p`, and `.ret_val(idx, p)` to constrain the value
    returned at ABI position `idx`.
    """
    def preceded_by(self, p: PatLike) -> "RetPat": ...
    def ret_val(self, idx: int, p: PatLike) -> "RetPat": ...
    def any_input(self, p: PatLike) -> "RetPat": ...
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def into_pat(self) -> Pat: ...

class IfPat:
    """Builder for `If` node patterns.  Returned by `if_else()`.

    Chain `.cond(p)`, `.true_branch(p)`, `.false_branch(p)`.  When
    `cond` is set the matcher also tries the compiler-inverted layout
    (`Not(cond)` with branches swapped).
    """
    def cond(self, p: PatLike) -> "IfPat": ...
    def true_branch(self, p: PatLike) -> "IfPat": ...
    def false_branch(self, p: PatLike) -> "IfPat": ...
    def capture_true(self, c: Capture) -> "IfPat": ...
    def capture_false(self, c: Capture) -> "IfPat": ...
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def into_pat(self) -> Pat: ...

class LoadPat:
    """Builder for `Load` node patterns.  Returned by `load()`.

    Chain `.addr(p)`, `.mem_in(p)`, `.bit_width(n)`, `.space(s)`,
    `.stack_only()`.
    """
    def addr(self, p: PatLike) -> "LoadPat": ...
    def mem_in(self, p: PatLike) -> "LoadPat": ...
    def any_input(self, p: PatLike) -> "LoadPat": ...
    def bit_width(self, n: int) -> "LoadPat": ...
    def space(self, s: object) -> "LoadPat": ...
    def stack_offset(self, k: int) -> "LoadPat": ...
    def stack_only(self) -> "LoadPat": ...
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def into_pat(self) -> Pat: ...

class StorePat:
    """Builder for `Store` node patterns.  Returned by `store()`.

    Chain `.addr(p)`, `.data(p)`, `.mem_in(p)`,
    `.bit_width(n)`, `.space(s)`, `.stack_only()`.
    """
    def addr(self, p: PatLike) -> "StorePat": ...
    def data(self, p: PatLike) -> "StorePat": ...
    def mem_in(self, p: PatLike) -> "StorePat": ...
    def any_input(self, p: PatLike) -> "StorePat": ...
    def bit_width(self, n: int) -> "StorePat": ...
    def space(self, s: object) -> "StorePat": ...
    def stack_offset(self, k: int) -> "StorePat": ...
    def stack_only(self) -> "StorePat": ...
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def into_pat(self) -> Pat: ...

class PhiPat:
    """Builder for tagged-`Phi` node patterns.  Returned by `phi()` /
    `phi_for(vn)`.  Chain `.for_vn(vn)` and `.input(idx, p)`."""
    def for_vn(self, vn: object) -> "PhiPat": ...
    def input(self, idx: int, p: PatLike) -> "PhiPat": ...
    def any_input(self, p: PatLike) -> "PhiPat": ...
    def phi_token(self, p: PatLike) -> "PhiPat": ...
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def into_pat(self) -> Pat: ...

class MemPhiPat:
    """Builder for `MemPhi` node patterns.  Returned by `mem_phi()`.
    Chain `.input(idx, p)` to constrain a predecessor's memory token."""
    def input(self, idx: int, p: PatLike) -> "MemPhiPat": ...
    def any_input(self, p: PatLike) -> "MemPhiPat": ...
    def phi_token(self, p: PatLike) -> "MemPhiPat": ...
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def into_pat(self) -> Pat: ...

class CallOutputPat:
    """A single sibling output slot of a `Call`, returned by
    `CallPat.output(slot)`.  Each constraint method records the
    constraint and returns the parent `CallPat` for further chaining."""
    def capture(self, c: Capture) -> CallPat: ...
    def of_width(self, bits: int) -> CallPat: ...
    def of_type(self, ty: str) -> CallPat: ...

class EntryPat:
    """Builder for the function's unique `Entry` node.  Returned by
    `entry()`.  `Entry` has no inputs and one control output, so it nests
    as a control operand (e.g. `region().any_input(entry())`)."""
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def into_pat(self) -> Pat: ...

class RegionPat:
    """Builder for `Region` (CFG-merge) node patterns.  Returned by
    `region()`.  Chain `.input(idx, p)` / `.any_input(p)` to constrain a
    control predecessor."""
    def input(self, idx: int, p: PatLike) -> "RegionPat": ...
    def any_input(self, p: PatLike) -> "RegionPat": ...
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def into_pat(self) -> Pat: ...

class IndirectBranchPat:
    """Builder for `IndirectBranch` node patterns.  Returned by
    `indirect_branch()`.  Chain `.target(p)` / `.mem(p)`."""
    def target(self, p: PatLike) -> "IndirectBranchPat": ...
    def mem(self, p: PatLike) -> "IndirectBranchPat": ...
    def any_input(self, p: PatLike) -> "IndirectBranchPat": ...
    def preceded_by(self, p: PatLike) -> "IndirectBranchPat": ...
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def into_pat(self) -> Pat: ...

class UnreachablePat:
    """Builder for `Unreachable` terminator patterns.  Returned by
    `unreachable()`."""
    def any_input(self, p: PatLike) -> "UnreachablePat": ...
    def preceded_by(self, p: PatLike) -> "UnreachablePat": ...
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def into_pat(self) -> Pat: ...

class SwitchPat:
    """Builder for `Switch` node patterns.  Returned by `switch()`.
    Chain `.address(p)` to constrain the dispatch address."""
    def address(self, p: PatLike) -> "SwitchPat": ...
    def any_input(self, p: PatLike) -> "SwitchPat": ...
    def preceded_by(self, p: PatLike) -> "SwitchPat": ...
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def into_pat(self) -> Pat: ...

class FunctionArgPat:
    """Builder for function-argument patterns.  Returned by
    `function_arg(i)` / `function_arg_any()` / `function_arg_reg(vn)` /
    `function_arg_stack(space, offset)`.  Chain `.index(i)`,
    `.source_register(vn)`, `.source_stack(space, offset)`."""
    def index(self, i: int) -> "FunctionArgPat": ...
    def source_register(self, vn: object) -> "FunctionArgPat": ...
    def source_stack(self, space: object, offset: int) -> "FunctionArgPat": ...
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def into_pat(self) -> Pat: ...

# ── Wildcards / consts / phi / initial ────────────────────────────────

def anything() -> Pat:
    """Wildcard: matches any node without binding it."""
def var(c: Capture) -> Pat:
    """Wildcard that binds the matched node to capture `c`."""
def predicate(f: Callable[[Match], bool]) -> Pat:
    """Match any node subject to a Python predicate; shorthand for
    `anything().when(f)`."""
def value_of_width(n: int) -> Pat:
    """OUTPUT-side: match any value whose own output is exactly `n` bits
    wide. Width 1 means "produces a bool" — which INCLUDES comparisons,
    since a comparison's output is `I1` however wide its operands are.
    The chained form is `Pat.of_width(n)`."""
def bool_value() -> Pat:
    """OUTPUT-side: match any value producing a boolean (1-bit `I1`).
    Exactly `value_of_width(1)`, named for intent. INCLUDES comparisons.
    The chained form is `Pat.bool_valued()`."""
def inputs_of_width(n: int, inner: PatLike) -> Pat:
    """INPUT-side: match `inner` and require all of ITS VALUE INPUTS to be
    `n` bits wide. Width 1 means "operates on bools" — which EXCLUDES
    comparisons, whose operands are typically wider than their `I1`
    result. This is the input-side counterpart of `value_of_width`."""
def bool_inputs(inner: PatLike) -> Pat:
    """INPUT-side: match `inner` whose value inputs are all booleans
    (1-bit `I1`). Exactly `inputs_of_width(1, inner)`, named for intent.
    EXCLUDES comparisons — see `inputs_of_width`."""
def int_const(value: int) -> Pat:
    """Match an `IntConst` whose value (masked to its output width)
    equals `value`."""
def signed_int_const(value: int) -> Pat:
    """Match an `IntConst` equal to the signed `value` across both sign-
    and zero-extended storage forms."""
def int_const_any_of(values: List[int]) -> Pat:
    """Match an `IntConst` equal to any value in `values`
    (set-membership variant of `int_const`)."""
def bool_const(value: bool) -> Pat:
    """Match an `I1` boolean constant equal to `value`."""
def float_const(bits: int) -> Pat:
    """Match a `FloatConst` whose raw bits equal `bits`."""
def any_int_const(c: Capture | None = ...) -> Pat:
    """Match any `IntConst`, optionally binding its value to `c`.  Omit `c` to
    match any integer constant purely as a structural constraint."""
def any_bool_const(c: Capture | None = ...) -> Pat:
    """Match any `I1` boolean constant, optionally binding it to `c`."""
def any_float_const(c: Capture | None = ...) -> Pat:
    """Match any `FloatConst`, optionally binding it to `c`."""
def initial_var() -> Pat:
    """Match any `InitialVar` node (an initial-state register read)."""
def initial_var_for(vn: object) -> Pat:
    """Match `InitialVar(vn)` for a specific varnode."""
def one_of(patterns: List[PatLike]) -> Pat:
    """Match a value if **any** of the listed sub-patterns matches it.

    An alternation, for the "optional wrapper" case — e.g. an address that may
    or may not be masked:
    `one_of([add(base, off), int_and(add(base, off), mask)])`. Match-only (not
    usable as a rewrite replacement); requires at least one alternative.

    **Order the alternatives most-specific first.** They are tried in order and
    the first match wins, so a permissive alternative placed before a narrower
    one shadows it — and because the shadowing arm still matches, the query
    silently returns the wrong binding rather than failing. `anything()` /
    `var(c)` match ANY node, including the operator a later arm was meant to
    catch::

        # WRONG: var(base) also matches the Add, so `off` never binds and
        # every `base + K` load silently looks like a bare `base`.
        load(addr=one_of([var(base), add(var(base), any_int_const(off))]))

        # RIGHT: specific shape first, bare fallback last.
        load(addr=one_of([add(var(base), any_int_const(off)), var(base)]))

    Captures under an alternative that did not fire are left UNBOUND (not
    defaulted), so `Match.has(c)` tells you which arm fired and lets you supply
    your own default: `off = h.const_uint(o) if h.has(o) else 0`."""
def function_arg(i: int) -> FunctionArgPat:
    """Start a function-argument pattern constrained to argument index `i`."""
def function_arg_any() -> FunctionArgPat:
    """Start a function-argument pattern matching any argument index."""
def function_arg_reg(vn: object) -> FunctionArgPat:
    """Match a function argument sourced from register varnode `vn`."""
def function_arg_stack(space: object, offset: int) -> FunctionArgPat:
    """Match a function argument sourced from the stack at `(space, offset)`."""
def phi() -> PhiPat:
    """Start a tagged-`Phi` pattern builder."""
def phi_for(vn: object) -> PhiPat:
    """Start a tagged-`Phi` pattern builder for a specific varnode."""
def mem_phi() -> MemPhiPat:
    """Start a `MemPhi` (memory-token phi) pattern builder."""
def entry() -> EntryPat:
    """Match the function's unique `Entry` node.  Nests as a control
    operand, e.g. `region().any_input(entry())`."""
def region() -> RegionPat:
    """Match any CFG-merge `Region` node."""
def indirect_branch() -> IndirectBranchPat:
    """Start an `IndirectBranch` (unresolved indirect jump) pattern
    builder."""
def unreachable() -> UnreachablePat:
    """Start an `Unreachable` terminator pattern builder."""
def switch() -> SwitchPat:
    """Start a `Switch` (resolved multi-way dispatch) pattern builder."""

# ── Integer binary ops ────────────────────────────────────────────────

def add(l: PatLike, r: PatLike) -> Pat: ...
def sub(l: PatLike, r: PatLike) -> Pat: ...
def mul(l: PatLike, r: PatLike) -> Pat: ...
def div(l: PatLike, r: PatLike) -> Pat: ...
def sdiv(l: PatLike, r: PatLike) -> Pat: ...
def rem(l: PatLike, r: PatLike) -> Pat: ...
def srem(l: PatLike, r: PatLike) -> Pat: ...
def shl(l: PatLike, r: PatLike) -> Pat: ...
def shr(l: PatLike, r: PatLike) -> Pat: ...
def sshr(l: PatLike, r: PatLike) -> Pat: ...
def int_and(l: PatLike, r: PatLike) -> Pat: ...
def int_or(l: PatLike, r: PatLike) -> Pat: ...
def int_xor(l: PatLike, r: PatLike) -> Pat: ...
def int_cmp(op: IntCmpOpName, l: PatLike, r: PatLike) -> Pat:
    """Match a specific `IntCmpOp` variant (e.g. `"Equal"`, `"Less"`,
    `"Sless"`, `"Carry"`)."""
def int_eq(l: PatLike, r: PatLike) -> Pat: ...
def int_ne(l: PatLike, r: PatLike) -> Pat: ...
def int_lt(l: PatLike, r: PatLike) -> Pat: ...
def int_le(l: PatLike, r: PatLike) -> Pat: ...
def int_slt(l: PatLike, r: PatLike) -> Pat: ...
def int_sle(l: PatLike, r: PatLike) -> Pat: ...
def int_carry(l: PatLike, r: PatLike) -> Pat: ...
def int_scarry(l: PatLike, r: PatLike) -> Pat: ...
def int_sborrow(l: PatLike, r: PatLike) -> Pat: ...

# ── Integer unary ops ────────────────────────────────────────────────

def neg(operand: PatLike) -> Pat: ...
def int_not(operand: PatLike) -> Pat:
    """Bitwise complement (`~x`) — `Xor(x, all_ones)`."""

# ── Bool binary / unary ops ──────────────────────────────────────────

def bool_and(l: PatLike, r: PatLike) -> Pat: ...
def bool_or(l: PatLike, r: PatLike) -> Pat: ...
def bool_xor(l: PatLike, r: PatLike) -> Pat: ...
def bool_not(operand: PatLike) -> Pat: ...

# ── Float ops ────────────────────────────────────────────────────────

def float_add(l: PatLike, r: PatLike) -> Pat: ...
def float_sub(l: PatLike, r: PatLike) -> Pat: ...
def float_mul(l: PatLike, r: PatLike) -> Pat: ...
def float_div(l: PatLike, r: PatLike) -> Pat: ...
def float_neg(operand: PatLike) -> Pat: ...
def float_abs(operand: PatLike) -> Pat: ...
def float_sqrt(operand: PatLike) -> Pat: ...
def float_ceil(operand: PatLike) -> Pat: ...
def float_floor(operand: PatLike) -> Pat: ...
def float_round(operand: PatLike) -> Pat: ...
def float_is_nan(operand: PatLike) -> Pat: ...
def float_eq(l: PatLike, r: PatLike) -> Pat: ...
def float_ne(l: PatLike, r: PatLike) -> Pat: ...
def float_lt(l: PatLike, r: PatLike) -> Pat: ...
def float_le(l: PatLike, r: PatLike) -> Pat: ...

# ── Conversions / bitcasts ───────────────────────────────────────────

def int_to_float(operand: PatLike) -> Pat: ...
def float_to_int(operand: PatLike) -> Pat: ...
def float_to_float(operand: PatLike) -> Pat: ...
def int_bits_to_float(operand: PatLike) -> Pat: ...
def float_bits_to_int(operand: PatLike) -> Pat: ...

# ── Width ops ────────────────────────────────────────────────────────

def truncate(operand: PatLike) -> Pat: ...
def popcount(operand: PatLike) -> Pat: ...
def lzcount(operand: PatLike) -> Pat: ...
def zero_extend(operand: PatLike) -> Pat: ...
def sign_extend(operand: PatLike) -> Pat: ...
def extend(op: ExtendOpName, operand: PatLike) -> Pat: ...

# ── Memory & control flow ────────────────────────────────────────────

def load(addr: PatLike = ...) -> LoadPat: ...
def store(addr: PatLike = ..., data: PatLike = ...) -> StorePat: ...
def call(at: Optional[int] = ...) -> CallPat: ...
def call_other() -> CallOtherPat: ...
def ret() -> RetPat: ...
def if_else(cond: PatLike = ...) -> IfPat: ...

# ── Typed family dispatchers ─────────────────────────────────────────

def int_binary(op: str, l: PatLike, r: PatLike) -> IntBinaryPat: ...
def bool_binary(op: str, l: PatLike, r: PatLike) -> BoolBinaryPat:
    """Boolean binary pattern (`"And"` / `"Or"` / `"Xor"`).  Booleans
    are 1-bit ints, so this is `IntBinaryOp` at `I1` (commutative,
    `I1`-output guarded).  Returns a chainable `BoolBinaryPat` — call
    `.ordered()` to disable commutative matching (symmetric with
    `int_binary` / `float_binary`)."""
def float_binary(op: str, l: PatLike, r: PatLike) -> FloatBinaryPat: ...

# ── Variant-agnostic ─────────────────────────────────────────────────

def int_bin_any(c: Capture, l: PatLike, r: PatLike) -> Pat: ...
def int_un_any(c: Capture, operand: PatLike) -> Pat: ...
def int_cmp_any(c: Capture, l: PatLike, r: PatLike) -> Pat: ...
def bool_bin_any(c: Capture, l: PatLike, r: PatLike) -> Pat: ...
# `bool_un_any` was removed alongside `IntUnaryOp::BitNot`: a 1-bit
# logical NOT is `Xor(_, IntConst(1)):I1` (canonical post-removal-of-
# BitNot), matched via `bool_bin_any` with an all-ones-I1 operand.
def float_bin_any(c: Capture, l: PatLike, r: PatLike) -> Pat: ...
def float_un_any(c: Capture, operand: PatLike) -> Pat: ...
def float_cmp_any(c: Capture, l: PatLike, r: PatLike) -> Pat: ...
