[package]
name = "strider-cfg"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Machine bytes to a control-flow graph of basic-block regions, via Sleigh."
repository.workspace = true
rust-version.workspace = true

[dependencies]
strider-target.workspace = true
dot.workspace = true
rsleigh.workspace = true
anyhow.workspace = true
petgraph.workspace = true
rustc-hash = "2"

[dev-dependencies]
strider-reader.workspace = true
object.workspace = true

[lints]
workspace = true
