[package]
name = "strider-cfg"
version = "0.1.0"
edition.workspace = true

[dependencies]
strider-target.workspace = true
dot.workspace = true
rsleigh.workspace = true
anyhow.workspace = true
petgraph.workspace = true
rustc-hash = "2"

[dev-dependencies]
strider-reader.workspace = true
object.workspace = true

[lints]
workspace = true
