"""Type stubs for the strider Python bindings.

These mirror the surface defined in crates/strider-py/src/.  Coverage
in v1 is not exhaustive — it covers the entry points that show up in
the README/usage examples.  Expand as the API grows.
"""

from __future__ import annotations

from typing import Any, Callable, ClassVar, Iterable, List, Optional, Tuple

__version__: str

# ── Architecture / calling convention ───────────────────────────────────

class SleighArch:
    @classmethod
    def x86_64(cls) -> SleighArch: ...
    @classmethod
    def x86(cls) -> SleighArch: ...
    @classmethod
    def mipsbe32(cls) -> SleighArch: ...
    @classmethod
    def mipsle32(cls) -> SleighArch: ...
    @classmethod
    def mipsbe64(cls) -> SleighArch: ...
    @classmethod
    def mipsle64(cls) -> SleighArch: ...
    @classmethod
    def arm(cls) -> SleighArch: ...
    @classmethod
    def arm_be(cls) -> SleighArch: ...
    @classmethod
    def arm_thumb(cls) -> SleighArch: ...
    @classmethod
    def aarch64(cls) -> SleighArch: ...
    @classmethod
    def aarch64be(cls) -> SleighArch: ...
    @classmethod
    def ppc32be(cls) -> SleighArch: ...
    @classmethod
    def ppc32le(cls) -> SleighArch: ...
    @classmethod
    def ppc64be(cls) -> SleighArch: ...
    @classmethod
    def ppc64le(cls) -> SleighArch: ...
    def name(self) -> str: ...

class CallingConvention:
    @classmethod
    def x86_64_systemv(cls) -> CallingConvention: ...
    @classmethod
    def aarch64_aapcs64(cls) -> CallingConvention: ...
    @classmethod
    def arm_aapcs(cls) -> CallingConvention: ...
    @classmethod
    def mips_o32(cls) -> CallingConvention: ...
    @classmethod
    def mips_n64(cls) -> CallingConvention: ...
    @classmethod
    def powerpc_sysv32(cls) -> CallingConvention: ...
    @classmethod
    def powerpc64_elf_v1(cls) -> CallingConvention: ...
    @classmethod
    def powerpc64_elf_v2(cls) -> CallingConvention: ...
    @classmethod
    def x86_cdecl(cls) -> CallingConvention: ...
    @classmethod
    def x86_64_all_preserving(cls) -> CallingConvention:
        """All-preserving x86_64 CC (every caller-clobbered register is
        listed callee-saved); a per-address override for transparent
        sites like `__fentry__` / `mcount`."""
        ...
    # Linux kernel presets.
    @classmethod
    def x86_linux_kernel(cls) -> CallingConvention: ...
    @classmethod
    def x86_64_linux_kernel(cls) -> CallingConvention: ...
    @classmethod
    def aarch64_linux_kernel(cls) -> CallingConvention: ...
    @classmethod
    def arm_linux_kernel(cls) -> CallingConvention: ...
    @classmethod
    def mips_linux_kernel_o32(cls) -> CallingConvention: ...
    @classmethod
    def mips_linux_kernel_n64(cls) -> CallingConvention: ...
    # Linux syscall ABIs.
    @classmethod
    def x86_linux_syscall(cls) -> CallingConvention: ...
    @classmethod
    def x86_64_linux_syscall(cls) -> CallingConvention: ...
    @classmethod
    def aarch64_linux_syscall(cls) -> CallingConvention: ...
    @classmethod
    def arm_linux_syscall(cls) -> CallingConvention: ...
    @classmethod
    def mips_linux_syscall_o32(cls) -> CallingConvention: ...
    @classmethod
    def mips_linux_syscall_n64(cls) -> CallingConvention: ...
    @classmethod
    def custom(
        cls,
        sleigh: "Sleigh",
        arg_passing_regs: list[str],
        callee_saved_regs: list[str],
        ret_val_regs: list[str],
        ret_val_regs_float: list[str],
        stack_pointer: str,
        stack_arg_offsets: list[int],
        ret_stack_pop: int,
        link_register: Optional[str] = ...,
        no_memory_clobber: bool = ...,
    ) -> CallingConvention: ...
    def name(self) -> str: ...

# ── Memory readers ──────────────────────────────────────────────────────

class MemoryMap:
    """Data-only fast-path reader.  Implements both the sleigh fetch
    and ReadOnlyMemory roles internally; the same MemoryMap can serve
    `mem=` and `rom=` arguments to `strider.run`.
    """
    def __init__(self) -> None: ...
    def add_region(self, start_addr: int, data: bytes) -> None: ...
    def add_region_from_elf(self, path: str, apply_relocations: bool = ...) -> None: ...
    def apply_elf_relocations(self, path: str) -> "RelocationStats": ...
    def set_endianness(self, endianness: str) -> None: ...
    def region_count(self) -> int: ...
    def read(self, addr: int, size: int) -> Optional[bytes]: ...
    def symbol(self, name: str) -> int: ...
    def symbol_size(self, name: str) -> Optional[int]: ...
    def function_max_size(self, name: str) -> tuple[int, Optional[int]]: ...
    def symbols(self) -> dict[str, int]: ...
    def entry_point(self) -> int: ...

class RelocationStats:
    seen: int
    applied: int
    skipped_unresolved_target: int
    skipped_unsupported_kind: int
    skipped_no_region: int
    unsupported_r_types: List[int]

class MemReader:
    """Subclass and override `read(addr, size) -> Optional[bytes]` to
    feed the analysis pipeline from a Python data source.  Each `read`
    crosses the Rust↔Python boundary; prefer `MemoryMap` for
    in-process bulk data.
    """

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def read(self, addr: int, size: int) -> Optional[bytes]: ...

class ReadOnlyMemory:
    """Subclass and override `read(addr, size) -> Optional[int]` to
    back a `LoadReadOnly` opt pass with Python data.  Returns up to 8
    bytes at `addr` decoded as a target-endian `int`; the implementation
    is responsible for byte order.  Returns `None` for unmapped
    addresses or sizes > 8.

    The pass only invokes `read` for RAM loads — non-RAM spaces
    (REGISTER, CONST, UNIQUE) are short-circuited by the adapter
    before reaching Python, so subclasses don't need to filter on
    space.
    """

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def read(self, addr: int, size: int) -> Optional[int]: ...

# ── Sleigh / CFG / Strider ──────────────────────────────────────────────

class VnSpace:
    """One of Sleigh's built-in address spaces."""
    @classmethod
    def ram(cls) -> VnSpace: ...
    @classmethod
    def register(cls) -> VnSpace: ...
    @classmethod
    def const_(cls) -> VnSpace: ...
    @classmethod
    def unique(cls) -> VnSpace: ...
    def name(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Vn:
    """A Sleigh varnode — `(space, offset, size_in_bytes)`."""
    def __init__(self, space: VnSpace, off: int, size: int) -> None: ...
    @property
    def space(self) -> VnSpace: ...
    @property
    def off(self) -> int: ...
    @property
    def size(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Sleigh:
    def __init__(self, arch: SleighArch, mem: Any) -> None: ...
    def arch_name(self) -> str: ...
    def reg(self, name: str) -> Optional[Vn]:
        """Look up a register by Sleigh name; `None` when not a register."""
        ...

class Cfg:
    def to_html(self, path: str, style: Optional[str] = ...) -> None: ...
    def to_dot(self, path: str) -> None: ...
    def html_str(self, style: Optional[str] = ...) -> str: ...

def build_cfg(
    sleigh: Sleigh,
    entry: int,
    allow_code_before_start_addr: bool = ...,
    function_max_size: Optional[int] = ...,
) -> Cfg: ...

class AnalyzeOutcome:
    function: Function
    unresolved_branch_count: int
    region_count: int

class Strider:
    def __init__(
        self, arch: SleighArch, sleigh: Sleigh, cc: CallingConvention
    ) -> None: ...
    def analyze_cfg(self, cfg: Cfg) -> AnalyzeOutcome: ...
    def build_optimizer_pipeline(self) -> OptimizerPipeline: ...
    def build_stable_optimizer_pipeline(self) -> OptimizerPipeline: ...
    def build_destructive_optimizer_pipeline(self) -> OptimizerPipeline: ...

class Function:
    def to_html(self, path: str, style: Optional[str] = ...) -> None: ...
    def to_dot(self, path: str) -> None: ...
    def html_str(self, style: Optional[str] = ...) -> str: ...
    def raw_dot_str(self) -> str: ...
    def raw_html_str(self) -> str: ...
    def to_raw_dot(self, path: str) -> None: ...
    def to_raw_html(self, path: str) -> None: ...
    def node_count(self) -> int: ...
    def count_loop_headers(self) -> int:
        """Count of `Region` join nodes reachable from entry."""
        ...
    def node_ids(self) -> List[int]:
        """All reachable node ids as raw integers."""
        ...
    def node_kind(self, node_id: int) -> str:
        """The `NodeKind` of `node_id` formatted as a string."""
        ...
    def asm_fingerprint(self, node_id: int) -> List[int]:
        """Sorted, deduped asm-instruction addresses recorded on `node_id`."""
        ...
    def wide_const_bytes(self, node_id: int) -> Optional[bytes]:
        """Raw LE bytes of an `IntConstWide` node, else `None`."""
        ...
    def call_other_name(self, node_id: int) -> Optional[str]:
        """Sleigh user-op name attached to a `CallOther` node, else `None`."""
        ...
    def compact(self) -> None:
        """Drop every node unreachable from entry; invalidates node ids."""
        ...
    def validate(self) -> Optional[str]:
        """Re-validate the graph; `None` on success, else an error message."""
        ...
    def optimize(self, pipeline: OptimizerPipeline) -> None: ...
    def reoptimize(self, destructive: bool = ...) -> None: ...
    def find_all(
        self,
        pat: Any,  # strider.pattern.PatLike
        ignore_casts: bool = ...,
        ignore_regions: bool = ...,
        ignore_casts_mask: Optional[Any] = ...,  # strider.pattern.CastMask
    ) -> List[Match]: ...
    def find_all_requirements(
        self,
        pats: List[Any],  # list[strider.pattern.PatLike]
        ignore_casts: bool = ...,
        ignore_regions: bool = ...,
        ignore_casts_mask: Optional[Any] = ...,  # strider.pattern.CastMask
    ) -> List[List[Match]]:
        """Run multiple patterns and intersect their matches on shared
        `Capture` objects; one inner list per joined match."""
        ...
    def rewrite(self, find: Any, replace: Any) -> int: ...
    def rewrite_all(self, pairs: List[Tuple[Any, Any]]) -> int: ...

class Match:
    @property
    def root(self) -> int:
        """The root node where the top-level pattern matched, as a `u32`
        node id."""
        ...
    def uint(self, key: Any) -> Optional[int]: ...
    def int(self, key: Any) -> Optional[int]: ...
    def bool(self, key: Any) -> Optional[bool]: ...
    def float_bits(self, key: Any) -> Optional[int]: ...
    def has(self, key: Any) -> bool: ...
    def int_binary_op(self, key: Any) -> Optional[str]:
        """Recover the matched `IntBinaryOp` variant name from `key`."""
        ...
    def int_unary_op(self, key: Any) -> Optional[str]:
        """Recover the matched `IntUnaryOp` variant name from `key`."""
        ...
    def int_cmp_op(self, key: Any) -> Optional[str]:
        """Recover the matched `IntCmpOp` variant name from `key`."""
        ...
    def bool_binary_op(self, key: Any) -> Optional[str]:
        """Recover the matched boolean binary op (`IntBinaryOp` at `I1`) name."""
        ...
    def bool_unary_op(self, key: Any) -> Optional[str]:
        """Recover the matched boolean unary op (`IntUnaryOp` at `I1`) name."""
        ...
    def float_binary_op(self, key: Any) -> Optional[str]:
        """Recover the matched `FloatBinaryOp` variant name from `key`."""
        ...
    def float_unary_op(self, key: Any) -> Optional[str]:
        """Recover the matched `FloatUnaryOp` variant name from `key`."""
        ...
    def float_cmp_op(self, key: Any) -> Optional[str]:
        """Recover the matched `FloatCmpOp` variant name from `key`."""
        ...
    def vn(self, key: Any) -> Optional[Vn]:
        """Recover the varnode bound by `key` (InitialVar / tagged Phi /
        FunctionArg node), else `None`."""
        ...
    def captured_offset(self, c: Any) -> Optional[int]:
        """The SP-relative stack offset bound by a `LoadPat`/`StorePat`
        `offset_capture(c)`, else `None`."""
        ...
    def asm_fingerprint(self, key: Any) -> List[int]: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __contains__(self, key: Any) -> bool: ...

class OptimizerPipeline:
    @classmethod
    def empty(cls) -> OptimizerPipeline: ...
    @classmethod
    def default(cls) -> OptimizerPipeline: ...
    @classmethod
    def stable_default(cls) -> OptimizerPipeline: ...
    @classmethod
    def destructive_default(cls) -> OptimizerPipeline: ...
    def add(self, pass_obj: Any) -> None: ...
    def add_post(self, pass_obj: Any) -> None: ...
    def pass_count(self) -> int: ...
    def post_pass_count(self) -> int: ...

class RunResult:
    cfg: Cfg
    function: Function
    sleigh: Sleigh

def run(
    arch: SleighArch,
    cc: CallingConvention,
    mem: Any,  # MemoryMap | MemReader subclass
    entry: int,
    rom: Optional[Any] = ...,  # MemoryMap | ReadOnlyMemory subclass
    pipeline: Optional[OptimizerPipeline] = ...,
    allow_code_before_start_addr: bool = ...,
    function_max_size: Optional[int] = ...,
    compact: bool = ...,
    per_address_ccs: Optional[dict[int, CallingConvention]] = ...,
) -> RunResult: ...

# ── Subpackages ────────────────────────────────────────────────────────

# Exception base class — also re-exported as strider.errors.StriderError.
class StriderError(Exception):
    """The single exception type raised by strider.  Every Rust error
    lands here carrying an informative message; the hierarchy is flat
    (no typed subclasses)."""
    ...
