"""Type stubs for the strider Python bindings.

These mirror the surface defined in crates/strider-py/src/.  Coverage
in v1 is not exhaustive — it covers the entry points that show up in
the README/usage examples.  Expand as the API grows.
"""

from __future__ import annotations

from typing import Any, Callable, ClassVar, Iterable, List, Optional, Tuple

__version__: str

# ── Architecture / calling convention ───────────────────────────────────

class SleighArch:
    @classmethod
    def x86_64(cls) -> SleighArch: ...
    @classmethod
    def x86(cls) -> SleighArch: ...
    @classmethod
    def mipsbe32(cls) -> SleighArch: ...
    @classmethod
    def mipsle32(cls) -> SleighArch: ...
    @classmethod
    def mipsbe64(cls) -> SleighArch: ...
    @classmethod
    def mipsle64(cls) -> SleighArch: ...
    @classmethod
    def arm(cls) -> SleighArch: ...
    @classmethod
    def arm_be(cls) -> SleighArch: ...
    @classmethod
    def arm_thumb(cls) -> SleighArch: ...
    @classmethod
    def aarch64(cls) -> SleighArch: ...
    @classmethod
    def aarch64be(cls) -> SleighArch: ...
    @classmethod
    def ppc32be(cls) -> SleighArch: ...
    @classmethod
    def ppc32le(cls) -> SleighArch: ...
    @classmethod
    def ppc64be(cls) -> SleighArch: ...
    @classmethod
    def ppc64le(cls) -> SleighArch: ...
    def name(self) -> str: ...

class CallingConvention:
    @classmethod
    def x86_64_systemv_abi(cls) -> CallingConvention: ...
    @classmethod
    def aarch64_aapcs64(cls) -> CallingConvention: ...
    @classmethod
    def arm_aapcs(cls) -> CallingConvention: ...
    @classmethod
    def mips_o32(cls) -> CallingConvention: ...
    @classmethod
    def mips_n64(cls) -> CallingConvention: ...
    @classmethod
    def powerpc_sysv32(cls) -> CallingConvention: ...
    @classmethod
    def powerpc64_elf_v1(cls) -> CallingConvention: ...
    @classmethod
    def powerpc64_elf_v2(cls) -> CallingConvention: ...
    @classmethod
    def x86_cdecl(cls) -> CallingConvention: ...
    def name(self) -> str: ...

# ── Memory readers ──────────────────────────────────────────────────────

class MemoryMap:
    """Data-only fast-path reader.  Implements both the sleigh fetch
    and ReadOnlyMemory roles internally; the same MemoryMap can serve
    `mem=` and `rom=` arguments to `strider.run`.
    """
    def __init__(self) -> None: ...
    def add_region(self, start_addr: int, data: bytes) -> None: ...
    def add_region_from_elf(self, path: str) -> None: ...
    def region_count(self) -> int: ...
    def read(self, addr: int, size: int) -> Optional[bytes]: ...
    def symbol(self, name: str) -> int: ...
    def symbols(self) -> dict[str, int]: ...
    def entry_point(self) -> int: ...

class MemReader:
    """Subclass and override `read(addr, size) -> Optional[bytes]` to
    feed the analysis pipeline from a Python data source.  Each `read`
    crosses the Rust↔Python boundary; prefer `MemoryMap` for
    in-process bulk data.
    """

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def read(self, addr: int, size: int) -> Optional[bytes]: ...

class ReadOnlyMemory:
    """Subclass and override `read(space_id, addr, size) -> Optional[int]`
    to back a `LoadReadOnly` opt pass with Python data.  Returned
    integer is the little-endian-decoded value.
    """

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def read(self, space_id: int, addr: int, size: int) -> Optional[int]: ...

# ── Sleigh / CFG / Strider ──────────────────────────────────────────────

class Sleigh:
    def __init__(self, arch: SleighArch, mem: Any) -> None: ...
    def arch_name(self) -> str: ...

class Cfg:
    def to_html(self, path: str, style: Optional[str] = ...) -> None: ...
    def to_dot(self, path: str) -> None: ...
    def html_str(self, style: Optional[str] = ...) -> str: ...

def build_cfg(
    sleigh: Sleigh,
    entry: int,
    allow_code_before_start_addr: bool = ...,
    function_max_size: Optional[int] = ...,
) -> Cfg: ...

class AnalyzeOutcome:
    graph: Graph
    unresolved_branch_count: int
    region_count: int

class Strider:
    def __init__(
        self, arch: SleighArch, sleigh: Sleigh, cc: CallingConvention
    ) -> None: ...
    def analyze_cfg(self, cfg: Cfg) -> AnalyzeOutcome: ...
    def build_optimizer_pipeline(self) -> OptimizerPipeline: ...
    def build_stable_optimizer_pipeline(self) -> OptimizerPipeline: ...
    def build_destructive_optimizer_pipeline(self) -> OptimizerPipeline: ...

class Graph:
    def to_html(self, path: str, style: Optional[str] = ...) -> None: ...
    def to_dot(self, path: str) -> None: ...
    def html_str(self, style: Optional[str] = ...) -> str: ...
    def node_count(self) -> int: ...
    def optimize(self, pipeline: OptimizerPipeline) -> None: ...
    def reoptimize(self, destructive: bool = ...) -> None: ...
    def find_all(
        self,
        pat: Any,  # strider.pattern.Pat
        ignore_casts: bool = ...,
        ignore_control_states: bool = ...,
    ) -> List[Match]: ...
    def rewrite(self, find: Any, replace: Any) -> int: ...
    def rewrite_all(self, pairs: List[Tuple[Any, Any]]) -> int: ...

class Match:
    def uint(self, key: Any) -> Optional[int]: ...
    def int(self, key: Any) -> Optional[int]: ...
    def bool(self, key: Any) -> Optional[bool]: ...
    def float_bits(self, key: Any) -> Optional[int]: ...
    def has(self, key: Any) -> bool: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __contains__(self, key: Any) -> bool: ...

class OptimizerPipeline:
    @classmethod
    def empty(cls) -> OptimizerPipeline: ...
    @classmethod
    def default(cls) -> OptimizerPipeline: ...
    @classmethod
    def stable_default(cls) -> OptimizerPipeline: ...
    @classmethod
    def destructive_default(cls) -> OptimizerPipeline: ...
    def add(self, pass_obj: Any) -> None: ...
    def add_post(self, pass_obj: Any) -> None: ...
    def pass_count(self) -> int: ...
    def post_pass_count(self) -> int: ...

class RunResult:
    cfg: Cfg
    graph: Graph
    sleigh: Sleigh

def run(
    *,
    arch: SleighArch,
    cc: CallingConvention,
    mem: Any,  # MemoryMap | MemReader subclass
    entry: int,
    rom: Optional[Any] = ...,  # MemoryMap | ReadOnlyMemory subclass
    pipeline: Optional[OptimizerPipeline] = ...,
    allow_code_before_start_addr: bool = ...,
    function_max_size: Optional[int] = ...,
) -> RunResult: ...

# ── Subpackages ────────────────────────────────────────────────────────

# Exception base class — also re-exported as strider.errors.StriderError.
class StriderError(Exception): ...
