"""Type stubs for strider.errors."""

from __future__ import annotations

class StriderError(Exception): ...
class LiftError(StriderError): ...
class ReaderError(StriderError): ...
class PatternError(StriderError): ...
class RewriteError(StriderError): ...
class UnresolvedIndirectBranchError(StriderError): ...
class UnknownCallOtherError(StriderError): ...
