"""Type stubs for strider.pattern — the match-side pattern DSL.

`Pat` is the LHS of a `find` / `rewrite` query (match-only affordances:
`.when()`, commutativity, `.of_width()`, `.value_ty()`, wildcards). For a
rewrite RHS (`replace=`), use the build-side `strider.template` module and
its `Template` type instead — `Function.rewrite`/`rewrite_all` type
`replace` as `Template`. A bare `Pat` is still accepted there for
back-compat (only its build-valid subset compiles: no `.when`, no
wildcard, no commutativity), but `strider.template` is the documented
path.
"""

from __future__ import annotations

from typing import Any, Callable, List, Optional, Union

from . import Match

class Capture:
    """Opaque capture variable; bind a matched node and read it back
    from the `Match`."""
    def __init__(self) -> None: ...

class CastMask:
    """Bitset selecting which value-passthrough cast `NodeKind`s the
    matcher walks through transparently.  Compose with `|`; pass to
    `Function.find_all(pat, ignore_casts_mask=...)`."""
    @classmethod
    def zero_extend(cls) -> CastMask: ...
    @classmethod
    def sign_extend(cls) -> CastMask: ...
    @classmethod
    def extend(cls) -> CastMask: ...
    @classmethod
    def truncate(cls) -> CastMask: ...
    @classmethod
    def int_bits_to_float(cls) -> CastMask: ...
    @classmethod
    def float_bits_to_int(cls) -> CastMask: ...
    @classmethod
    def all(cls) -> CastMask: ...
    @classmethod
    def none(cls) -> CastMask: ...
    @classmethod
    def empty(cls) -> CastMask: ...

class JoinConstraint:
    """A CFG relation between two captured entities. Construct via
    `dominates` / `reaches` / `not_reaches`; pass to
    `Function.find_all([...], constraints=[...])`."""
    def bits(self) -> int: ...
    def __or__(self, other: CastMask) -> CastMask: ...
    def __and__(self, other: CastMask) -> CastMask: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Pat:
    """Opaque finalised match pattern — the LHS of a `find` / `rewrite`
    query.  Built by the free constructors and chained via `.capture` /
    `.cap` / `.when` / `.ordered` / `.of_width` / `.value_ty` /
    `.bool_valued`.  For the rewrite RHS, build a `strider.template.Template`
    instead (see that module)."""
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def ordered(self) -> Pat: ...
    def of_width(self, n: int) -> Pat: ...
    def value_ty(self, ty: str) -> Pat: ...
    def bool_valued(self) -> Pat: ...

# All builders accept str | Capture | Pat (or one of the typed builders
# below) for sub-patterns.  The typed-builder variants are auto-finalised
# at field-setter call sites — see `CallPat.into_pat()` for the explicit
# form.  This union mirrors the Rust `PatLike` `FromPyObject` enum.
PatLike = Union[
    str,
    Capture,
    Pat,
    "CallPat",
    "CallOtherPat",
    "RetPat",
    "IfPat",
    "LoadPat",
    "StorePat",
    "PhiPat",
    "MemPhiPat",
    "FunctionArgPat",
    "IntBinaryPat",
    "FloatBinaryPat",
    "BoolBinaryPat",
]

# ── Typed family-dispatcher builder types ──────────────────────────────

class IntBinaryPat:
    """Builder for an integer binary-op pattern (returned by
    `int_binary`).  `.ordered()` is terminal — it finalises to a
    `Pat`; the other finalisers also return `Pat`."""
    def ordered(self) -> Pat: ...
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def into_pat(self) -> Pat: ...

class FloatBinaryPat:
    """Builder for a float binary-op pattern (returned by
    `float_binary`).  `.ordered()` is terminal — it finalises to a
    `Pat`; the other finalisers also return `Pat`."""
    def ordered(self) -> Pat: ...
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def into_pat(self) -> Pat: ...

class BoolBinaryPat:
    """Builder for a boolean binary-op pattern (returned by
    `bool_binary`).  Booleans are the 1-bit integer `I1`, so this builds
    an `IntBinaryOp` (`And` / `Or` / `Xor`) at `I1` with an `I1`-output
    guard (it never matches a same-shaped wide integer op).  `.ordered()`
    is terminal — it finalises to a `Pat`; the other finalisers also
    return `Pat`."""
    def ordered(self) -> Pat: ...
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def into_pat(self) -> Pat: ...

class CallPat:
    """Builder for `Call` node patterns.  Returned by `call()`.

    Field-setter methods (`at`, `at_any`, `target`, `arg`) return the same
    builder for chaining; finaliser methods (`capture`, `cap`, `when`,
    `into_pat`) return a `Pat`.

    `Function.find_all` / `Function.rewrite` accept un-finalised builders
    via `PatLike`, so `g.find_all(call().arg(0, int_const(8)))` works
    without an explicit `.into_pat()`.
    """
    def at(self, addr: int) -> "CallPat": ...
    def at_any(self, addrs: List[int]) -> "CallPat": ...
    def target(self, p: PatLike) -> "CallPat": ...
    def arg(self, idx: int, p: PatLike) -> "CallPat": ...
    def res(self) -> "CallPat": ...
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def into_pat(self) -> Pat: ...

class CallOtherPat:
    """Builder for `CallOther` node patterns.  Returned by `call_other()`.

    Chain `.user_op_id(v)` to constrain the user-op id, `.name(s)` to
    constrain the user-op name (read from the side table), and
    `.arg(idx, p)` for individual arguments.
    """
    def user_op_id(self, v: int) -> "CallOtherPat": ...
    def name(self, n: str) -> "CallOtherPat": ...
    def arg(self, idx: int, p: PatLike) -> "CallOtherPat": ...
    def ctrl(self, p: PatLike) -> "CallOtherPat": ...
    def mem(self, p: PatLike) -> "CallOtherPat": ...
    def res(self) -> "CallOtherPat": ...
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def into_pat(self) -> Pat: ...

class RetPat:
    """Builder for `Return` node patterns.  Returned by `ret()`.

    Chain `.preceded_by(p)` to match Returns whose direct ctrl
    predecessor is `p`, and `.ret_val(idx, p)` to constrain the value
    returned at ABI position `idx`.
    """
    def preceded_by(self, p: PatLike) -> "RetPat": ...
    def ret_val(self, idx: int, p: PatLike) -> "RetPat": ...
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def into_pat(self) -> Pat: ...

class IfPat:
    """Builder for `If` node patterns.  Returned by `if_else()`.

    Chain `.cond(p)`, `.true_branch(p)`, `.false_branch(p)`.  When
    `cond` is set the matcher also tries the compiler-inverted layout
    (`Not(cond)` with branches swapped).
    """
    def cond(self, p: PatLike) -> "IfPat": ...
    def true_branch(self, p: PatLike) -> "IfPat": ...
    def false_branch(self, p: PatLike) -> "IfPat": ...
    def capture_true(self, c: Capture) -> "IfPat": ...
    def capture_false(self, c: Capture) -> "IfPat": ...
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def into_pat(self) -> Pat: ...

class LoadPat:
    """Builder for `Load` node patterns.  Returned by `load()`.

    Chain `.addr(p)`, `.mem_in(p)`, `.bit_width(n)`, `.space(s)`,
    `.stack_only()`.
    """
    def addr(self, p: PatLike) -> "LoadPat": ...
    def mem_in(self, p: PatLike) -> "LoadPat": ...
    def bit_width(self, n: int) -> "LoadPat": ...
    def space(self, s: object) -> "LoadPat": ...
    def stack_offset(self, k: int) -> "LoadPat": ...
    def stack_only(self) -> "LoadPat": ...
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def into_pat(self) -> Pat: ...

class StorePat:
    """Builder for `Store` node patterns.  Returned by `store()`.

    Chain `.addr(p)`, `.data(p)`, `.mem_in(p)`,
    `.bit_width(n)`, `.space(s)`, `.stack_only()`.
    """
    def addr(self, p: PatLike) -> "StorePat": ...
    def data(self, p: PatLike) -> "StorePat": ...
    def mem_in(self, p: PatLike) -> "StorePat": ...
    def bit_width(self, n: int) -> "StorePat": ...
    def space(self, s: object) -> "StorePat": ...
    def stack_offset(self, k: int) -> "StorePat": ...
    def stack_only(self) -> "StorePat": ...
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def into_pat(self) -> Pat: ...

class PhiPat:
    """Builder for tagged-`Phi` node patterns.  Returned by `phi()` /
    `phi_for(vn)`.  Chain `.for_vn(vn)` and `.input(idx, p)`."""
    def for_vn(self, vn: object) -> "PhiPat": ...
    def input(self, idx: int, p: PatLike) -> "PhiPat": ...
    def any_input(self, p: PatLike) -> "PhiPat": ...
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def into_pat(self) -> Pat: ...

class MemPhiPat:
    """Builder for `MemPhi` node patterns.  Returned by `mem_phi()`.
    Chain `.input(idx, p)` to constrain a predecessor's memory token."""
    def input(self, idx: int, p: PatLike) -> "MemPhiPat": ...
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def into_pat(self) -> Pat: ...

class FunctionArgPat:
    """Builder for function-argument patterns.  Returned by
    `function_arg(i)` / `function_arg_any()` / `function_arg_reg(vn)` /
    `function_arg_stack(space, offset)`.  Chain `.index(i)`,
    `.source_register(vn)`, `.source_stack(space, offset)`."""
    def index(self, i: int) -> "FunctionArgPat": ...
    def source_register(self, vn: object) -> "FunctionArgPat": ...
    def source_stack(self, space: object, offset: int) -> "FunctionArgPat": ...
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...
    def when(self, f: Callable[[Match], bool]) -> Pat: ...
    def into_pat(self) -> Pat: ...

# ── Wildcards / consts / phi / initial ────────────────────────────────

def anything() -> Pat:
    """Wildcard: matches any node without binding it."""
def var(c: Capture) -> Pat:
    """Wildcard that binds the matched node to capture `c`."""
def predicate(f: Callable[[Match], bool]) -> Pat:
    """Match any node subject to a Python predicate; shorthand for
    `anything().when(f)`."""
def value_of_width(n: int) -> Pat:
    """Match any value output exactly `n` bits wide (output-width filter)."""
def bool_value() -> Pat:
    """Match any boolean value (any 1-bit `I1` value output)."""
def inputs_of_width(n: int, inner: PatLike) -> Pat:
    """Match `inner` and require all of its value inputs to be `n` bits
    wide (input-width filter)."""
def bool_inputs(inner: PatLike) -> Pat:
    """Match `inner` whose value inputs are all booleans (1-bit `I1`)."""
def int_const(value: int) -> Pat:
    """Match an `IntConst` whose value (masked to its output width)
    equals `value`."""
def signed_int_const(value: int) -> Pat:
    """Match an `IntConst` equal to the signed `value` across both sign-
    and zero-extended storage forms."""
def int_const_any_of(values: List[int]) -> Pat:
    """Match an `IntConst` equal to any value in `values`
    (set-membership variant of `int_const`)."""
def bool_const(value: bool) -> Pat:
    """Match an `I1` boolean constant equal to `value`."""
def float_const(bits: int) -> Pat:
    """Match a `FloatConst` whose raw bits equal `bits`."""
def any_int_const(c: Capture | None = ...) -> Pat:
    """Match any `IntConst`, optionally binding its value to `c`.  Omit `c` to
    match any integer constant purely as a structural constraint."""
def any_bool_const(c: Capture | None = ...) -> Pat:
    """Match any `I1` boolean constant, optionally binding it to `c`."""
def any_float_const(c: Capture | None = ...) -> Pat:
    """Match any `FloatConst`, optionally binding it to `c`."""
def initial_var() -> Pat:
    """Match any `InitialVar` node (an initial-state register read)."""
def initial_var_for(vn: object) -> Pat:
    """Match `InitialVar(vn)` for a specific varnode."""
def one_of(patterns: List[PatLike]) -> Pat:
    """Match a value if **any** of the listed sub-patterns matches it.

    An alternation, for the "optional wrapper" case — e.g. an address that may
    or may not be masked:
    `one_of([add(base, off), int_and(add(base, off), mask)])`. Alternatives are
    tried in order. Match-only (not usable as a rewrite replacement); requires
    at least one alternative."""
def dominates(a: Capture, b: Capture) -> JoinConstraint:
    """`a` dominates `b` in the control subgraph. Pass to
    `Function.find_all([...], constraints=[...])`."""
def reaches(src: Capture, dst: Capture) -> JoinConstraint:
    """`dst` is forward-control-reachable from the branch edge `src` (an `If`'s
    `capture_true`/`capture_false` value). Isolates one arm plus the shared
    post-merge tail."""
def not_reaches(src: Capture, dst: Capture) -> JoinConstraint:
    """The negation of `reaches`. Pair `reaches(true_edge, c)` with
    `not_reaches(false_edge, c)` to select exclusively-true-arm nodes."""
def dominated_by_branch(branch: Capture, node: Capture) -> JoinConstraint:
    """`node` is dominated by the target of branch edge `branch` — in that
    block exclusively. A single `dominated_by_branch(true_edge, c)` means
    "`c` is in the true block" (no paired `not_reaches` needed)."""
def function_arg(i: int) -> FunctionArgPat:
    """Start a function-argument pattern constrained to argument index `i`."""
def function_arg_any() -> FunctionArgPat:
    """Start a function-argument pattern matching any argument index."""
def function_arg_reg(vn: object) -> FunctionArgPat:
    """Match a function argument sourced from register varnode `vn`."""
def function_arg_stack(space: object, offset: int) -> FunctionArgPat:
    """Match a function argument sourced from the stack at `(space, offset)`."""
def phi() -> PhiPat:
    """Start a tagged-`Phi` pattern builder."""
def phi_for(vn: object) -> PhiPat:
    """Start a tagged-`Phi` pattern builder for a specific varnode."""
def mem_phi() -> MemPhiPat:
    """Start a `MemPhi` (memory-token phi) pattern builder."""

# ── Integer binary ops ────────────────────────────────────────────────

def add(l: PatLike, r: PatLike) -> Pat: ...
def sub(l: PatLike, r: PatLike) -> Pat: ...
def mul(l: PatLike, r: PatLike) -> Pat: ...
def div(l: PatLike, r: PatLike) -> Pat: ...
def sdiv(l: PatLike, r: PatLike) -> Pat: ...
def rem(l: PatLike, r: PatLike) -> Pat: ...
def srem(l: PatLike, r: PatLike) -> Pat: ...
def shl(l: PatLike, r: PatLike) -> Pat: ...
def shr(l: PatLike, r: PatLike) -> Pat: ...
def sshr(l: PatLike, r: PatLike) -> Pat: ...
def int_and(l: PatLike, r: PatLike) -> Pat: ...
def int_or(l: PatLike, r: PatLike) -> Pat: ...
def int_xor(l: PatLike, r: PatLike) -> Pat: ...
def int_cmp(op: str, l: PatLike, r: PatLike) -> Pat:
    """Match a specific `IntCmpOp` variant (e.g. `"Equal"`, `"Less"`,
    `"Sless"`, `"Carry"`)."""
def int_eq(l: PatLike, r: PatLike) -> Pat: ...
def int_ne(l: PatLike, r: PatLike) -> Pat: ...
def int_lt(l: PatLike, r: PatLike) -> Pat: ...
def int_le(l: PatLike, r: PatLike) -> Pat: ...
def int_slt(l: PatLike, r: PatLike) -> Pat: ...
def int_sle(l: PatLike, r: PatLike) -> Pat: ...
def int_carry(l: PatLike, r: PatLike) -> Pat: ...
def int_scarry(l: PatLike, r: PatLike) -> Pat: ...
def int_sborrow(l: PatLike, r: PatLike) -> Pat: ...

# ── Integer unary ops ────────────────────────────────────────────────

def neg(operand: PatLike) -> Pat: ...
def int_not(operand: PatLike) -> Pat:
    """Bitwise complement (`~x`) — `Xor(x, all_ones)`."""

# ── Bool binary / unary ops ──────────────────────────────────────────

def bool_and(l: PatLike, r: PatLike) -> Pat: ...
def bool_or(l: PatLike, r: PatLike) -> Pat: ...
def bool_xor(l: PatLike, r: PatLike) -> Pat: ...
def bool_not(operand: PatLike) -> Pat: ...

# ── Float ops ────────────────────────────────────────────────────────

def float_add(l: PatLike, r: PatLike) -> Pat: ...
def float_sub(l: PatLike, r: PatLike) -> Pat: ...
def float_mul(l: PatLike, r: PatLike) -> Pat: ...
def float_div(l: PatLike, r: PatLike) -> Pat: ...
def float_neg(operand: PatLike) -> Pat: ...
def float_abs(operand: PatLike) -> Pat: ...
def float_sqrt(operand: PatLike) -> Pat: ...
def float_ceil(operand: PatLike) -> Pat: ...
def float_floor(operand: PatLike) -> Pat: ...
def float_round(operand: PatLike) -> Pat: ...
def float_is_nan(operand: PatLike) -> Pat: ...
def float_eq(l: PatLike, r: PatLike) -> Pat: ...
def float_ne(l: PatLike, r: PatLike) -> Pat: ...
def float_lt(l: PatLike, r: PatLike) -> Pat: ...
def float_le(l: PatLike, r: PatLike) -> Pat: ...

# ── Conversions / bitcasts ───────────────────────────────────────────

def int_to_float(operand: PatLike) -> Pat: ...
def float_to_int(operand: PatLike) -> Pat: ...
def float_to_float(operand: PatLike) -> Pat: ...
def int_bits_to_float(operand: PatLike) -> Pat: ...
def float_bits_to_int(operand: PatLike) -> Pat: ...

# ── Width ops ────────────────────────────────────────────────────────

def truncate(operand: PatLike) -> Pat: ...
def popcount(operand: PatLike) -> Pat: ...
def lzcount(operand: PatLike) -> Pat: ...
def zero_extend(operand: PatLike) -> Pat: ...
def sign_extend(operand: PatLike) -> Pat: ...
def extend(op: str, operand: PatLike) -> Pat: ...

# ── Memory & control flow ────────────────────────────────────────────

def load(addr: PatLike = ...) -> LoadPat: ...
def store(addr: PatLike = ..., data: PatLike = ...) -> StorePat: ...
def call(at: Optional[int] = ...) -> CallPat: ...
def call_other() -> CallOtherPat: ...
def ret() -> RetPat: ...
def if_else(cond: PatLike = ...) -> IfPat: ...

# ── Typed family dispatchers ─────────────────────────────────────────

def int_binary(op: str, l: PatLike, r: PatLike) -> IntBinaryPat: ...
def bool_binary(op: str, l: PatLike, r: PatLike) -> BoolBinaryPat:
    """Boolean binary pattern (`"And"` / `"Or"` / `"Xor"`).  Booleans
    are 1-bit ints, so this is `IntBinaryOp` at `I1` (commutative,
    `I1`-output guarded).  Returns a chainable `BoolBinaryPat` — call
    `.ordered()` to disable commutative matching (symmetric with
    `int_binary` / `float_binary`)."""
def float_binary(op: str, l: PatLike, r: PatLike) -> FloatBinaryPat: ...

# ── Variant-agnostic ─────────────────────────────────────────────────

def int_bin_any(c: Capture, l: PatLike, r: PatLike) -> Pat: ...
def int_un_any(c: Capture, operand: PatLike) -> Pat: ...
def int_cmp_any(c: Capture, l: PatLike, r: PatLike) -> Pat: ...
def bool_bin_any(c: Capture, l: PatLike, r: PatLike) -> Pat: ...
# `bool_un_any` was removed alongside `IntUnaryOp::BitNot`: a 1-bit
# logical NOT is `Xor(_, IntConst(1)):I1` (canonical post-removal-of-
# BitNot), matched via `bool_bin_any` with an all-ones-I1 operand.
def float_bin_any(c: Capture, l: PatLike, r: PatLike) -> Pat: ...
def float_un_any(c: Capture, operand: PatLike) -> Pat: ...
def float_cmp_any(c: Capture, l: PatLike, r: PatLike) -> Pat: ...
