"""Type stubs for strider.pattern."""

from __future__ import annotations

from typing import Any, Union

class Capture:
    def __init__(self) -> None: ...

class Pat:
    def capture(self, c: Capture) -> Pat: ...
    def cap(self, name: str) -> Pat: ...

# All builders accept str | Capture | Pat for sub-patterns.
PatLike = Union[str, Capture, Pat]

def any_() -> Pat: ...
def var(c: Capture) -> Pat: ...
def int_const(value: int) -> Pat: ...
def bool_const(value: bool) -> Pat: ...
def any_int_const(c: Capture) -> Pat: ...
def any_bool_const(c: Capture) -> Pat: ...
def initial_var() -> Pat: ...
def function_arg(i: int) -> Pat: ...
def function_arg_any() -> Pat: ...
def phi() -> Pat: ...

# Integer binary ops.
def add(l: PatLike, r: PatLike) -> Pat: ...
def sub(l: PatLike, r: PatLike) -> Pat: ...
def mul(l: PatLike, r: PatLike) -> Pat: ...
def div(l: PatLike, r: PatLike) -> Pat: ...
def sdiv(l: PatLike, r: PatLike) -> Pat: ...
def rem(l: PatLike, r: PatLike) -> Pat: ...
def srem(l: PatLike, r: PatLike) -> Pat: ...
def shl(l: PatLike, r: PatLike) -> Pat: ...
def shr(l: PatLike, r: PatLike) -> Pat: ...
def sshr(l: PatLike, r: PatLike) -> Pat: ...
def and_(l: PatLike, r: PatLike) -> Pat: ...
def or_(l: PatLike, r: PatLike) -> Pat: ...
def xor(l: PatLike, r: PatLike) -> Pat: ...
def int_eq(l: PatLike, r: PatLike) -> Pat: ...
def int_lt(l: PatLike, r: PatLike) -> Pat: ...
def int_le(l: PatLike, r: PatLike) -> Pat: ...
def int_slt(l: PatLike, r: PatLike) -> Pat: ...
def int_sle(l: PatLike, r: PatLike) -> Pat: ...
def int_carry(l: PatLike, r: PatLike) -> Pat: ...
def int_scarry(l: PatLike, r: PatLike) -> Pat: ...
def int_sborrow(l: PatLike, r: PatLike) -> Pat: ...

# Bool ops.
def bool_and(l: PatLike, r: PatLike) -> Pat: ...
def bool_or(l: PatLike, r: PatLike) -> Pat: ...
def bool_xor(l: PatLike, r: PatLike) -> Pat: ...

# Memory & control flow.
def load(addr: PatLike = ...) -> Pat: ...
def store(addr: PatLike = ..., data: PatLike = ...) -> Pat: ...
def stack_store(offset: int = ..., data: PatLike = ...) -> Pat: ...
def call(at: int = ...) -> Pat: ...
def call_other() -> Pat: ...
def ret() -> Pat: ...
def if_(cond: PatLike = ...) -> Pat: ...
