"""Type stubs for strider.sleigh — architecture, calling convention, and
the low-level Sleigh / varnode surface."""

from __future__ import annotations

from typing import Any, Optional

# ── Architecture / calling convention ───────────────────────────────────

class SleighArch:
    @classmethod
    def x86_64(cls) -> SleighArch: ...
    @classmethod
    def x86(cls) -> SleighArch: ...
    @classmethod
    def mipsbe32(cls) -> SleighArch: ...
    @classmethod
    def mipsle32(cls) -> SleighArch: ...
    @classmethod
    def mipsbe64(cls) -> SleighArch: ...
    @classmethod
    def mipsle64(cls) -> SleighArch: ...
    @classmethod
    def arm(cls) -> SleighArch: ...
    @classmethod
    def arm_be(cls) -> SleighArch: ...
    @classmethod
    def arm_be_kernel(cls) -> SleighArch: ...
    @classmethod
    def arm_thumb(cls) -> SleighArch: ...
    @classmethod
    def aarch64(cls) -> SleighArch: ...
    @classmethod
    def aarch64be(cls) -> SleighArch: ...
    @classmethod
    def ppc32be(cls) -> SleighArch: ...
    @classmethod
    def ppc32le(cls) -> SleighArch: ...
    @classmethod
    def ppc64be(cls) -> SleighArch: ...
    @classmethod
    def ppc64le(cls) -> SleighArch: ...
    def name(self) -> str: ...

class CallingConvention:
    @classmethod
    def x86_64_systemv(cls) -> CallingConvention: ...
    @classmethod
    def aarch64_aapcs64(cls) -> CallingConvention: ...
    @classmethod
    def arm_aapcs(cls) -> CallingConvention: ...
    @classmethod
    def mips_o32(cls) -> CallingConvention: ...
    @classmethod
    def mips_n64(cls) -> CallingConvention: ...
    @classmethod
    def powerpc_sysv32(cls) -> CallingConvention: ...
    @classmethod
    def powerpc64_elf_v1(cls) -> CallingConvention: ...
    @classmethod
    def powerpc64_elf_v2(cls) -> CallingConvention: ...
    @classmethod
    def x86_cdecl(cls) -> CallingConvention: ...
    @classmethod
    def x86_64_all_preserving(cls) -> CallingConvention:
        """All-preserving x86_64 CC (every caller-clobbered register is
        listed callee-saved); a per-address override for transparent
        sites like `__fentry__` / `mcount`."""
        ...
    # The one Linux kernel-internal preset (x86 32-bit -mregparm=3); every
    # other arch's kernel CC equals its userland preset.  Syscalls are not
    # calling conventions — the syscall/int 0x80/svc traps lift to CallOther.
    @classmethod
    def x86_linux_kernel(cls) -> CallingConvention: ...
    @classmethod
    def custom(
        cls,
        sleigh: "Sleigh",
        arg_passing_regs: list[str],
        callee_saved_regs: list[str],
        ret_val_regs: list[str],
        ret_val_regs_float: list[str],
        stack_pointer: str,
        stack_arg_base: int | None,
        stack_arg_increment: int,
        ret_stack_pop: int,
        link_register: Optional[str] = ...,
        preserves_memory: bool = ...,
    ) -> CallingConvention: ...
    def name(self) -> str: ...

# ── Varnodes / Sleigh ───────────────────────────────────────────────────

class VnSpace:
    """One of Sleigh's built-in address spaces."""
    RAM: VnSpace
    REGISTER: VnSpace
    CONST: VnSpace
    UNIQUE: VnSpace
    def name(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Vn:
    """A Sleigh varnode — `(space, offset, size_in_bytes)`."""
    def __init__(self, space: VnSpace, off: int, size: int) -> None: ...
    @property
    def space(self) -> VnSpace: ...
    @property
    def off(self) -> int: ...
    @property
    def size(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Sleigh:
    def __init__(self, arch: SleighArch, mem: Any) -> None: ...
    def arch_name(self) -> str: ...
    def reg(self, name: str) -> Optional[Vn]:
        """Look up a register by Sleigh name; `None` when not a register."""
        ...
    def reg_name(self, vn: Vn) -> Optional[str]:
        """Reverse of `reg`: a varnode's Sleigh register name, or `None`
        when it names no register (non-REGISTER space, or an
        offset/size absent from this arch's table)."""
        ...
