"""Type stubs for strider.template — the build-side rewrite-RHS DSL.

`strider.pattern.Pat` is the match side (the `find` of a rewrite).
`strider.template.Template` is the build side (the `replace`): it exposes
only the build-valid subset of the pattern DSL — the node/op/const
constructors plus `var(capture)` — with no `.when()`, no commutativity
toggle, and no `.ordered()`, since those are match-only concepts with no
build-side meaning. `Function.rewrite(find, replace)` / `rewrite_all`
type `replace` as `Template`.
"""

from __future__ import annotations

from typing import Union

from .pattern import Capture

class Template:
    """Opaque, type-checked rewrite-RHS build expression. Construct via
    the free functions below; pass as `replace` to
    `Function.rewrite(find, replace)` / `Function.rewrite_all(pairs)`."""
    ...

# Any build-side operand slot accepts a `Template`, a bare `Capture`
# (sugar for `var(c)`), or a string (auto-interned to a `Capture`).
TemplateLike = Union[Template, Capture, str]

# ── Leaves ───────────────────────────────────────────────────────────

def var(c: Capture) -> Template:
    """Build-side substitution: at rewrite time, replaced by the node
    bound to `c` on the matched LHS. The one build-valid "wildcard" —
    there is no build-side `any()`."""
def int_const(value: int) -> Template:
    """Build an `IntConst` whose stored value (masked to output width)
    is `value`."""
def signed_int_const(value: int) -> Template:
    """Build a signed `IntConst` (`i64`-range `value`)."""
def bool_const(value: bool) -> Template:
    """Build an `I1` boolean constant equal to `value`."""
def float_const(bits: int) -> Template:
    """Build a `FloatConst` with raw bits `bits`."""

# ── Integer binary ops ──────────────────────────────────────────────

def add(l: TemplateLike, r: TemplateLike) -> Template: ...
def sub(l: TemplateLike, r: TemplateLike) -> Template:
    """Build integer subtraction `a - b` (lowers to `Add(a, Neg(b))`)."""
def mul(l: TemplateLike, r: TemplateLike) -> Template: ...
def div(l: TemplateLike, r: TemplateLike) -> Template: ...
def sdiv(l: TemplateLike, r: TemplateLike) -> Template: ...
def rem(l: TemplateLike, r: TemplateLike) -> Template: ...
def srem(l: TemplateLike, r: TemplateLike) -> Template: ...
def shl(l: TemplateLike, r: TemplateLike) -> Template: ...
def shr(l: TemplateLike, r: TemplateLike) -> Template: ...
def sshr(l: TemplateLike, r: TemplateLike) -> Template: ...
def and_(l: TemplateLike, r: TemplateLike) -> Template: ...
def or_(l: TemplateLike, r: TemplateLike) -> Template: ...
def xor(l: TemplateLike, r: TemplateLike) -> Template: ...

def int_cmp(op: str, l: TemplateLike, r: TemplateLike) -> Template:
    """Build a specific `IntCmpOp` variant by name (e.g. `"Equal"`,
    `"Less"`, `"Sless"`, `"Carry"`, `"Scarry"`, `"Sborrow"`)."""
def int_eq(l: TemplateLike, r: TemplateLike) -> Template: ...
def int_lt(l: TemplateLike, r: TemplateLike) -> Template: ...
def int_slt(l: TemplateLike, r: TemplateLike) -> Template: ...
def int_carry(l: TemplateLike, r: TemplateLike) -> Template: ...
def int_scarry(l: TemplateLike, r: TemplateLike) -> Template: ...
def int_sborrow(l: TemplateLike, r: TemplateLike) -> Template: ...

# ── Integer unary ops ────────────────────────────────────────────────

def neg(operand: TemplateLike) -> Template: ...
def bit_not(operand: TemplateLike) -> Template:
    """Bitwise complement (`~x`) — `Xor(x, all_ones)`."""
def not_(operand: TemplateLike) -> Template:
    """Alias for `bit_not` (`not` is a Python keyword)."""
def popcount(operand: TemplateLike) -> Template: ...
def lzcount(operand: TemplateLike) -> Template: ...

# ── Bool ops (booleans are the 1-bit integer `I1`) ──────────────────

def bool_and(l: TemplateLike, r: TemplateLike) -> Template: ...
def bool_or(l: TemplateLike, r: TemplateLike) -> Template: ...
def bool_xor(l: TemplateLike, r: TemplateLike) -> Template: ...
def bool_not(operand: TemplateLike) -> Template: ...

# ── Float ops ────────────────────────────────────────────────────────

def float_add(l: TemplateLike, r: TemplateLike) -> Template: ...
def float_sub(l: TemplateLike, r: TemplateLike) -> Template: ...
def float_mul(l: TemplateLike, r: TemplateLike) -> Template: ...
def float_div(l: TemplateLike, r: TemplateLike) -> Template: ...
def float_neg(operand: TemplateLike) -> Template: ...
def float_abs(operand: TemplateLike) -> Template: ...
def float_sqrt(operand: TemplateLike) -> Template: ...
def float_ceil(operand: TemplateLike) -> Template: ...
def float_floor(operand: TemplateLike) -> Template: ...
def float_round(operand: TemplateLike) -> Template: ...
def float_eq(l: TemplateLike, r: TemplateLike) -> Template: ...
def float_lt(l: TemplateLike, r: TemplateLike) -> Template: ...

# ── Conversions / bitcasts ───────────────────────────────────────────

def int_to_float(operand: TemplateLike) -> Template: ...
def float_to_int(operand: TemplateLike) -> Template: ...
def float_to_float(operand: TemplateLike) -> Template: ...
def int_bits_to_float(operand: TemplateLike) -> Template: ...
def float_bits_to_int(operand: TemplateLike) -> Template: ...

# ── Width ops ────────────────────────────────────────────────────────

def truncate(operand: TemplateLike) -> Template: ...
def zero_extend(operand: TemplateLike) -> Template: ...
def sign_extend(operand: TemplateLike) -> Template: ...
def extend(op: str, operand: TemplateLike) -> Template: ...
