//! Randomized oracle stress test for the dominance-frontier / iterated-DF
//! algorithms.
//!
//! Rather than eyeball the code against published pseudocode, this validates it
//! against the *set-theoretic definitions* over hundreds of random CFGs:
//!
//! * Dominator sets are recomputed independently by the textbook iterative
//!   data-flow fixpoint (`Dom(n) = {n} ∪ ⋂ Dom(pred)`), and immediate dominators
//!   are derived from them — an oracle that shares NO code with the module under
//!   test.
//! * `dominance_frontiers` is checked against the definition
//!   `DF(x) = { b : x dominates a predecessor of b ∧ x does not strictly
//!   dominate b }`.
//! * `phi_placement` is checked against the iterated-DF fixpoint
//!   `J = DF(Defs ∪ J)`.
//! * `dominator_tree_preorder` is checked for the after-idom invariant.
//!
//! Graphs are generated by a deterministic PRNG (reproducible; no `rand` dep):
//! a random spanning tree rooted at 0 (guarantees every node is reachable) plus
//! random extra forward / back / cross / self edges (reducible AND irreducible
//! shapes).

use std::collections::{HashMap, HashSet};

use graph_algorithms::dominance::{
    DomTree, dominance_frontiers, dominator_tree_preorder, phi_placement,
};

/// A concrete [`DomTree`] over `u32` nodes with explicit predecessor lists and
/// an explicit (oracle-computed) idom map.
struct Mock {
    nodes: Vec<u32>,
    preds: HashMap<u32, Vec<u32>>,
    idom: HashMap<u32, u32>,
}

impl DomTree for Mock {
    type Node = u32;
    fn nodes(&self) -> impl Iterator<Item = u32> + '_ {
        self.nodes.iter().copied()
    }
    fn predecessors(&self, n: u32) -> impl Iterator<Item = u32> + '_ {
        self.preds.get(&n).into_iter().flatten().copied()
    }
    fn immediate_dominator(&self, n: u32) -> Option<u32> {
        self.idom.get(&n).copied()
    }
}

/// Deterministic splitmix-ish PRNG (no external deps, reproducible).
struct Rng(u64);
impl Rng {
    fn next_u64(&mut self) -> u64 {
        // LCG step, then xorshift the high bits out for better low-bit quality.
        self.0 = self
            .0
            .wrapping_mul(6_364_136_223_846_793_005)
            .wrapping_add(1_442_695_040_888_963_407);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
        z ^ (z >> 27)
    }
    fn below(&mut self, n: u32) -> u32 {
        (self.next_u64() % u64::from(n)) as u32
    }
}

/// Build a random reachable CFG: `n` nodes (0 = entry), a random spanning tree
/// (edge from a random earlier node to each node → all reachable), plus `extra`
/// random edges (any direction, self-loops allowed).  Returns deduped
/// predecessor lists.
fn random_cfg(rng: &mut Rng, n: u32, extra: u32) -> HashMap<u32, Vec<u32>> {
    let mut edges: HashSet<(u32, u32)> = HashSet::new();
    for v in 1..n {
        let u = rng.below(v); // parent strictly earlier → acyclic tree, all reachable
        edges.insert((u, v));
    }
    for _ in 0..extra {
        let u = rng.below(n);
        let v = rng.below(n);
        if v != 0 {
            // keep the entry predecessor-free (a normalized CFG entry)
            edges.insert((u, v));
        }
    }
    let mut preds: HashMap<u32, Vec<u32>> = (0..n).map(|x| (x, Vec::new())).collect();
    for (u, v) in edges {
        preds.get_mut(&v).unwrap().push(u);
    }
    preds
}

/// ORACLE: dominator sets by the iterative data-flow fixpoint, then idoms.
/// Shares no code with the module under test.
fn oracle_dom_and_idom(
    n: u32,
    preds: &HashMap<u32, Vec<u32>>,
) -> (HashMap<u32, HashSet<u32>>, HashMap<u32, u32>) {
    let all: HashSet<u32> = (0..n).collect();
    let mut dom: HashMap<u32, HashSet<u32>> = HashMap::new();
    dom.insert(0, HashSet::from([0]));
    for x in 1..n {
        dom.insert(x, all.clone()); // start universal, shrink to fixpoint
    }
    let mut changed = true;
    while changed {
        changed = false;
        for x in 1..n {
            // ⋂ Dom(p) over predecessors, then ∪ {x}.
            let mut inter: Option<HashSet<u32>> = None;
            for &p in &preds[&x] {
                let dp = &dom[&p];
                inter = Some(match inter {
                    None => dp.clone(),
                    Some(acc) => acc.intersection(dp).copied().collect(),
                });
            }
            let mut new = inter.unwrap_or_default();
            new.insert(x);
            if new != dom[&x] {
                dom.insert(x, new);
                changed = true;
            }
        }
    }
    // idom(x) = the strict dominator with the largest dominator set (closest).
    let mut idom: HashMap<u32, u32> = HashMap::new();
    for x in 1..n {
        let best = dom[&x]
            .iter()
            .filter(|&&d| d != x)
            .max_by_key(|&&d| dom[&d].len());
        if let Some(&d) = best {
            idom.insert(x, d);
        }
    }
    (dom, idom)
}

/// ORACLE: `DF(x)` by definition — `b` such that `x` dominates some predecessor
/// of `b` and `x` does not strictly dominate `b`.
fn oracle_df(
    n: u32,
    preds: &HashMap<u32, Vec<u32>>,
    dom: &HashMap<u32, HashSet<u32>>,
) -> HashMap<u32, HashSet<u32>> {
    let dominates = |x: u32, y: u32| dom[&y].contains(&x); // x ∈ Dom(y)
    let strictly_dominates = |x: u32, y: u32| x != y && dominates(x, y);
    let mut df: HashMap<u32, HashSet<u32>> = (0..n).map(|x| (x, HashSet::new())).collect();
    for b in 0..n {
        for &p in &preds[&b] {
            for x in 0..n {
                if dominates(x, p) && !strictly_dominates(x, b) {
                    df.get_mut(&x).unwrap().insert(b);
                }
            }
        }
    }
    df
}

/// ORACLE: iterated dominance frontier of `defs` as the fixpoint `J = DF(defs ∪ J)`.
fn oracle_idf(df: &HashMap<u32, HashSet<u32>>, defs: &HashSet<u32>) -> HashSet<u32> {
    let mut j: HashSet<u32> = HashSet::new();
    loop {
        let mut next: HashSet<u32> = HashSet::new();
        for &x in defs.iter().chain(j.iter()) {
            if let Some(s) = df.get(&x) {
                next.extend(s.iter().copied());
            }
        }
        if next == j {
            return j;
        }
        j = next;
    }
}

fn as_set(v: &[u32]) -> HashSet<u32> {
    v.iter().copied().collect()
}

#[test]
fn dominance_frontiers_match_definition_over_random_cfgs() {
    let mut rng = Rng(0x1234_5678_9abc_def0);
    for iter in 0..600u32 {
        let n = 3 + rng.below(11); // 3..=13 nodes
        let extra = rng.below(2 * n); // up to ~2n extra edges (dense, irreducible)
        let preds = random_cfg(&mut rng, n, extra);
        let (dom, idom) = oracle_dom_and_idom(n, &preds);

        let mock = Mock {
            nodes: (0..n).collect(),
            preds: preds.clone(),
            idom: idom.clone(),
        };

        // DF: implementation vs definitional oracle, node by node.
        let df_impl = dominance_frontiers(&mock);
        // Same DF in the oracle's std representation, for the IDF fixpoint below.
        let df_std: HashMap<u32, HashSet<u32>> = df_impl
            .iter()
            .map(|(&k, v)| (k, v.iter().copied().collect()))
            .collect();
        let df_oracle = oracle_df(n, &preds, &dom);
        for x in 0..n {
            let got = df_impl.get(&x).map(|v| as_set(v)).unwrap_or_default();
            assert_eq!(
                got, df_oracle[&x],
                "iter {iter}: DF({x}) mismatch (n={n}, extra={extra})\npreds={preds:?}\nidom={idom:?}"
            );
        }

        // Preorder: root first, every node strictly after its idom, no dupes.
        let order = dominator_tree_preorder(&mock, 0);
        assert_eq!(order[0], 0, "iter {iter}: preorder must start at root");
        let pos: HashMap<u32, usize> = order.iter().enumerate().map(|(i, &nn)| (nn, i)).collect();
        assert_eq!(
            pos.len(),
            order.len(),
            "iter {iter}: preorder has duplicates"
        );
        for (&node, &id) in &idom {
            assert!(
                pos[&id] < pos[&node],
                "iter {iter}: node {node} must follow its idom {id}"
            );
        }

        // IDF / φ placement: for several random def sets, implementation vs
        // fixpoint oracle (both over the SAME impl DF map, isolating the
        // worklist logic).
        for _ in 0..4 {
            let defs: HashSet<u32> = (0..n).filter(|_| rng.below(3) == 0).collect();
            let defs: HashSet<u32> = if defs.is_empty() {
                HashSet::from([rng.below(n)])
            } else {
                defs
            };
            let dm: HashMap<(), Vec<u32>> = HashMap::from([((), defs.iter().copied().collect())]);
            let place = phi_placement(&df_impl, &dm);
            let phi_nodes: HashSet<u32> = place
                .iter()
                .filter(|(_, vars)| vars.contains(&()))
                .map(|(&nn, _)| nn)
                .collect();
            let idf_oracle = oracle_idf(&df_std, &defs);
            assert_eq!(
                phi_nodes, idf_oracle,
                "iter {iter}: IDF mismatch for defs={defs:?}\ndf={df_impl:?}"
            );
        }
    }
}

/// Nodes unreachable from the root (idom = None) must be skipped by
/// `dominance_frontiers` and excluded from the preorder — not panic, not appear.
#[test]
fn unreachable_nodes_are_skipped() {
    // 0 → 1 → 2 (reachable); 3 → 4 with no edge from {0,1,2} (unreachable island).
    let preds: HashMap<u32, Vec<u32>> = HashMap::from([
        (0, vec![]),
        (1, vec![0]),
        (2, vec![1]),
        (3, vec![]), // island root, not reachable from 0
        (4, vec![3]),
    ]);
    // Only reachable nodes get an idom; 3 and 4 are unreachable → None.
    let idom: HashMap<u32, u32> = HashMap::from([(1, 0), (2, 1)]);
    let mock = Mock {
        nodes: vec![0, 1, 2, 3, 4],
        preds,
        idom,
    };

    let df = dominance_frontiers(&mock);
    // A straight-line reachable chain has empty frontiers everywhere.
    for x in 0..5 {
        assert!(
            df.get(&x).is_none_or(|v| v.is_empty()),
            "DF({x}) must be empty"
        );
    }
    let order = dominator_tree_preorder(&mock, 0);
    assert_eq!(
        order,
        vec![0, 1, 2],
        "preorder excludes the unreachable island"
    );
}
